# -*- coding: utf-8 -*-
"""EEG_Correlation_Analysis_CLEAN (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9mARU-HuqEszKmI8Wva6XviUL4bFcgE

# 🧠 EEG-Stress Correlation Analysis: Clean Workflow
## SAM-40 Dataset: Feature Correlation & Channel Analysis

---

### **Workflow Overview:**
1. **Configuration** - Setup paths & channel exclusion
2. **Feature Extraction** - Extract 52 features from all files
3. **Correlation Analysis** - Compute feature-stress correlations
4. **Top/Bottom Features** - Select top 5 highest & bottom 5 weakest
5. **Per-Channel Extraction** - Extract channel-level values for selected features
6. **Channel Correlation** - Analyze which channels correlate with stress
7. **Comparison** - Compare high vs low correlation features

---

**Key Features:**
- ✅ Flexible channel exclusion (32 → 24 channels)
- ✅ Multi-index DataFrame for per-channel analysis
- ✅ Minimal output (only summaries)
- ✅ No data leakage from excluded channels

---
## STEP 0: Setup & Imports
"""

import os
import re
import numpy as np
import pandas as pd
import scipy.io as sio          # <-- added: for loading .mat files
from scipy import signal
from scipy.stats import entropy, pearsonr
from scipy.signal import welch, coherence, hilbert
import pywt
from pathlib import Path
from typing import Dict, List, Tuple
from tqdm.auto import tqdm
import warnings
warnings.filterwarnings('ignore')

# Mount Google Drive if using Colab
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=False)
    print("✓ Google Drive mounted")
except:
    print("✓ Running locally (skip Drive mount)")

print("✓ All libraries imported successfully")

"""---
## STEP 1: Configuration
### 🎯 **IMPORTANT:** Set your paths and channel exclusion here
"""

# ============================================================
# PATH CONFIGURATION - ADJUST TO YOUR SETUP
# ============================================================
DIR_FILTERED = '/content/drive/MyDrive/Thesis/dataset/SAM40/filteredData'
DIR_OUTPUT = '/content/drive/MyDrive/Thesis/correlation_analysis'
SCALES_FILE = '/content/drive/MyDrive/SAM40/Data/scales.xlsx'

# Dataset constants
FS = 128
N_CHANNELS = 32
N_SAMPLES = 3200
TASKS = ['Arithmetic', 'Stroop', 'Mirror_image']
TASK_MAP = {'Arithmetic': 'math', 'Stroop': 'stroop', 'Mirror_image': 'mirror'}

# All 32 channel names
CHANNEL_NAMES = [
    'CZ','FZ','Fp1','F7','F3','FC1','C3','FC5',
    'FT9','T7','CP5','CP1','P3','P7','PO9','O1',
    'PZ','OZ','O2','PO10','P8','P4','CP2','CP6',
    'T8','FT10','FC6','C4','FC2','F4','F8','Fp2'
]

# Set to True to exclude artifact-prone channels
USE_CHANNEL_EXCLUSION = False  # ← SET THIS

# Artifact-prone channels to exclude (literature-based)
EXCLUDE_CHANNELS = [
    'Fp1', 'Fp2',      # Eye artifacts
    'F7', 'F8',        # Muscle artifacts
    'FT9', 'FT10',     # Reference noise
    'PO9', 'PO10'      # Poor contact
]

# Derive working channel list
if USE_CHANNEL_EXCLUSION:
    CHANNELS_WORK = [ch for ch in CHANNEL_NAMES if ch not in EXCLUDE_CHANNELS]
    CH_INDICES = [i for i, ch in enumerate(CHANNEL_NAMES) if ch not in EXCLUDE_CHANNELS]
else:
    CHANNELS_WORK = CHANNEL_NAMES.copy()
    CH_INDICES = list(range(N_CHANNELS))

N_CHANNELS_WORK = len(CHANNELS_WORK)

# Create output directory
os.makedirs(DIR_OUTPUT, exist_ok=True)

print("="*80)
print("⚙️  CONFIGURATION SUMMARY")
print("="*80)
print(f"\n📁 Paths:")
print(f"   Data:   {DIR_FILTERED}")
print(f"   Output: {DIR_OUTPUT}")
print(f"   Scales: {SCALES_FILE}")

print(f"\n📊 Channel Configuration:")
print(f"   Channel exclusion: {'ENABLED' if USE_CHANNEL_EXCLUSION else 'DISABLED'}")
print(f"   Total channels: {N_CHANNELS}")
print(f"   Working channels: {N_CHANNELS_WORK}")
print(f"   Retention: {N_CHANNELS_WORK/N_CHANNELS*100:.0f}%")

if USE_CHANNEL_EXCLUSION:
    print(f"\n🚫 Excluded channels ({len(EXCLUDE_CHANNELS)}):")
    print(f"   {', '.join(EXCLUDE_CHANNELS)}")
    print(f"\n✅ Working channels ({N_CHANNELS_WORK}):")
    print(f"   {', '.join(CHANNELS_WORK)}")

print("\n" + "="*80)
print("✓ Configuration complete")
print("="*80)

"""---
## STEP 2: Utility Functions
### Helper functions for data loading and parsing
"""

def get_all_files(dir_path: str) -> List[str]:
    """Get all .mat files in directory."""
    files = sorted([os.path.join(dir_path, f) for f in os.listdir(dir_path)
                   if f.endswith('.mat') and not f.startswith('.')])
    return files

def parse_filename(filepath: str) -> Dict[str, any]:
    """Parse filename to extract metadata."""
    filename = os.path.basename(filepath)
    match = re.match(r'(\w+)_sub_(\d+)_trial(\d+)\.mat', filename)
    if match:
        return {
            'file_id': filename.replace('.mat', ''),
            'task': match.group(1),
            'subject': int(match.group(2)),
            'trial': int(match.group(3))
        }
    return None

MAT_KEY = 'Clean_data'  # key inside the .mat file that holds the EEG array

def load_eeg_file(filepath: str) -> np.ndarray:
    """
    Load EEG data from a .mat file.

    The .mat file stores data as (n_channels, n_samples) under the key
    MAT_KEY ('Clean_data'). We transpose it to (n_samples, n_channels)
    to match the format expected by all downstream feature functions.

    Returns:
        np.ndarray of shape (n_samples, n_channels), dtype float64
    """
    mat = sio.loadmat(filepath)

    if MAT_KEY not in mat:
        available = [k for k in mat.keys() if not k.startswith('_')]
        raise KeyError(
            f"Key '{MAT_KEY}' not found in {filepath}. "
            f"Available keys: {available}. "
            f"Update MAT_KEY at the top of this section if needed."
        )

    data = mat[MAT_KEY].astype(np.float64)   # shape: (n_channels, n_samples)
    return data.T                              # transpose -> (n_samples, n_channels)

def load_scales(scales_file: str) -> pd.DataFrame:
    """Load stress labels from scales file."""
    scales = pd.read_excel(scales_file)

    # Debug info
    print(f"\n📊 Scales file loaded:")
    print(f"   Shape: {scales.shape}")
    print(f"   Columns: {list(scales.columns)}")
    print(f"   Sample row 0: {scales.iloc[0].to_dict()}")

    return scales

def get_stress_label(task: str, subject: int, trial: int, scales_df: pd.DataFrame) -> int:
    """
    Get stress label for specific trial.

    Scales.xlsx format: t{trial}_{task}
    Example: t1_math, t2_stroop, t3_mirror

    Args:
        task: Task name (e.g., 'Arithmetic', 'Stroop', 'Mirror_image')
        subject: Subject number (1-40)
        trial: Trial number (1-3)
        scales_df: DataFrame with stress labels

    Returns:
        Stress label (1-10) or np.nan if not found
    """
    # Map task name to column suffix
    task_suffix = TASK_MAP.get(task)
    if task_suffix is None:
        return np.nan

    # Build column name: t{trial}_{task}
    # Example: t1_math, t2_stroop, t3_mirror
    col_name = f"t{trial}_{task_suffix}"

    # Check if column exists
    if col_name not in scales_df.columns:
        return np.nan

    # Check if subject index is valid
    if subject < 1 or subject > len(scales_df):
        return np.nan

    # Get label (subject indexing: subject 1 = row 0)
    try:
        label = scales_df.loc[subject - 1, col_name]

        # Convert to int if valid
        if pd.isna(label):
            return np.nan

        return int(label)

    except Exception as e:
        return np.nan

print("✓ Utility functions defined")

"""---
## STEP 3: Feature Extraction Functions
### All 52 features across 6 domains
"""

def extract_time_features(data: np.ndarray) -> Dict[str, float]:
    """Extract 13 time-domain features."""
    # Flatten across channels (average)
    flat = data.flatten()

    from scipy.stats import kurtosis, skew

    return {
        'time_MAV': np.mean(np.abs(flat)),
        'time_RMS': np.sqrt(np.mean(flat ** 2)),
        'time_STD': np.std(flat),
        'time_VAR': np.var(flat),
        'time_ZCR': float(np.sum(np.diff(np.sign(flat)) != 0)),
        'time_KURT': kurtosis(flat),
        'time_SKEW': skew(flat),
        'time_MEDIAN': np.median(flat),
        'time_PTP': np.ptp(flat),
        'time_ENERGY': np.sum(flat ** 2),
        'time_MIN': np.min(flat),
        'time_MAX': np.max(flat),
        'time_SAD': np.sum(np.abs(np.diff(flat)))
    }

def extract_frequency_features(data: np.ndarray, fs: int = 128) -> Dict[str, float]:
    """Extract 18 frequency-domain features."""
    # Average PSD across channels
    psds = []
    for ch in range(data.shape[1]):
        f, psd = welch(data[:, ch], fs=fs, nperseg=min(256, len(data[:, ch])))
        psds.append(psd)

    psd_avg = np.mean(psds, axis=0)

    # Band power
    def band_power(freqs, psd, fmin, fmax):
        idx = np.logical_and(freqs >= fmin, freqs <= fmax)
        return np.trapz(psd[idx], freqs[idx])

    delta = band_power(f, psd_avg, 1, 4)
    theta = band_power(f, psd_avg, 4, 8)
    alpha = band_power(f, psd_avg, 8, 13)
    beta = band_power(f, psd_avg, 13, 30)
    gamma = band_power(f, psd_avg, 30, 50)
    total = band_power(f, psd_avg, 1, 50)

    # Spectral descriptors
    mean_freq = np.sum(f * psd_avg) / np.sum(psd_avg)
    cum_psd = np.cumsum(psd_avg)
    median_freq = f[np.where(cum_psd >= cum_psd[-1] / 2)[0][0]]
    spread = np.sqrt(np.sum(((f - mean_freq) ** 2) * psd_avg) / np.sum(psd_avg))

    return {
        'freq_DELTA_power': delta,
        'freq_THETA_power': theta,
        'freq_ALPHA_power': alpha,
        'freq_BETA_power': beta,
        'freq_GAMMA_power': gamma,
        'freq_DELTA_rel': delta / total if total > 0 else 0,
        'freq_THETA_rel': theta / total if total > 0 else 0,
        'freq_ALPHA_rel': alpha / total if total > 0 else 0,
        'freq_BETA_rel': beta / total if total > 0 else 0,
        'freq_GAMMA_rel': gamma / total if total > 0 else 0,
        'freq_TOTAL_power': total,
        'freq_peak_freq': f[np.argmax(psd_avg)],
        'freq_mean_freq': mean_freq,
        'freq_median_freq': median_freq,
        'freq_spectral_spread': spread,
        'freq_spectral_skewness': np.sum(((f - mean_freq) ** 3) * psd_avg) / (spread ** 3 * np.sum(psd_avg)),
        'freq_spectral_kurtosis': np.sum(((f - mean_freq) ** 4) * psd_avg) / (spread ** 4 * np.sum(psd_avg)),
        'freq_theta_alpha_ratio': theta / alpha if alpha > 0 else 0
    }

def extract_time_frequency_features(data: np.ndarray, fs: int = 128) -> Dict[str, float]:
    """Extract 2 time-frequency features."""
    # Average across channels
    energies = []
    entropies = []

    for ch in range(data.shape[1]):
        _, _, Zxx = signal.stft(data[:, ch], fs=fs, nperseg=256, noverlap=128)
        S = np.abs(Zxx) ** 2
        energies.append(np.sum(S))

        S_norm = S / (np.sum(S) + 1e-12)
        entropies.append(-np.sum(S_norm * np.log(S_norm + 1e-12)))

    return {
        'tf_stft_energy': np.mean(energies),
        'tf_entropy': np.mean(entropies)
    }

def extract_wavelet_features(data: np.ndarray) -> Dict[str, float]:
    """Extract 7 wavelet features."""
    # Average across channels
    all_energies = [[] for _ in range(5)]  # L0-L4
    all_entropies = []

    for ch in range(data.shape[1]):
        coeffs = pywt.wavedec(data[:, ch], 'db4', level=4)
        for i, c in enumerate(coeffs):
            all_energies[i].append(np.sum(c ** 2))

        # Entropy
        ents = []
        for c in coeffs:
            if len(c) > 0:
                prob = np.abs(c) / (np.sum(np.abs(c)) + 1e-10)
                ents.append(entropy(prob + 1e-10))
        all_entropies.append(np.mean(ents))

    return {
        'wavelet_energy_L0': np.mean(all_energies[0]),
        'wavelet_energy_L1': np.mean(all_energies[1]),
        'wavelet_energy_L2': np.mean(all_energies[2]),
        'wavelet_energy_L3': np.mean(all_energies[3]),
        'wavelet_energy_L4': np.mean(all_energies[4]),
        'wavelet_total_energy': np.mean([np.sum(e) for e in all_energies]),
        'wavelet_mean_entropy': np.mean(all_entropies)
    }

def extract_connectivity_features(data: np.ndarray, fs: int = 128) -> Dict[str, float]:
    """Extract 8 connectivity features."""
    n_ch = data.shape[1]

    # Differential entropy (per-channel, then average)
    diff_ents = []
    for ch in range(n_ch):
        var = np.var(data[:, ch])
        if var > 0:
            diff_ents.append(0.5 * np.log(2 * np.pi * np.e * var))

    # Phase-based connectivity
    phases = np.angle(hilbert(data, axis=0))
    plv_vals = []
    pli_vals = []
    wpli_vals = []

    for i in range(n_ch):
        for j in range(i+1, n_ch):
            phase_diff = phases[:, i] - phases[:, j]

            # PLV
            plv_vals.append(np.abs(np.mean(np.exp(1j * phase_diff))))

            # PLI
            pli_vals.append(np.abs(np.mean(np.sign(np.sin(phase_diff)))))

            # wPLI
            imag = np.imag(np.exp(1j * phase_diff))
            denom = np.mean(np.abs(imag))
            wpli_vals.append(np.abs(np.mean(imag)) / denom if denom > 0 else 0)

    return {
        'conn_diff_entropy': np.mean(diff_ents),
        'conn_plv': np.mean(plv_vals),
        'conn_pli': np.mean(pli_vals),
        'conn_wpli': np.mean(wpli_vals)
    }

# # ── Approximate Entropy (ApEn) ──────────────────────────────
# def _apen(x: np.ndarray, m: int = 2, r_scale: float = 0.2) -> float:
#     """Approximate Entropy (ApEn). O(N) approximate implementation."""
#     N = len(x)
#     r = r_scale * np.std(x)
#     def phi(m_):
#         count = 0
#         for i in range(N - m_):
#             template = x[i:i + m_]
#             diffs = np.abs(x[np.arange(N - m_)[:, None] + np.arange(m_)] - template)
#             count += np.sum(np.max(diffs, axis=1) <= r)
#         return np.log(count / (N - m_)) if count > 0 else 0.0
#     # Downsample to max 512 points to keep speed reasonable
#     if N > 512:
#         step = N // 512
#         x = x[::step]
#         N = len(x)
#     try:
#         return float(phi(m) - phi(m + 1))
#     except Exception:
#         return 0.0

# # ── Permutation Entropy ─────────────────────────────────────
# def _perm_entropy(x: np.ndarray, order: int = 3, delay: int = 1) -> float:
#     """Permutation Entropy."""
#     N = len(x)
#     run_length = N - (order - 1) * delay
#     if run_length < 1:
#         return 0.0
#     from itertools import permutations
#     all_perms = {p: 0 for p in permutations(range(order))}
#     for i in range(run_length):
#         sub = x[i:i + order * delay:delay]
#         perm = tuple(np.argsort(sub))
#         all_perms[perm] += 1
#     counts = np.array(list(all_perms.values()), dtype=float)
#     counts = counts[counts > 0]
#     probs  = counts / counts.sum()
#     return float(-np.sum(probs * np.log(probs)))
# ── Higuchi Fractal Dimension ────────────────────────────────
def _higuchi_fd(x: np.ndarray, kmax: int = 8) -> float:
    """Higuchi Fractal Dimension."""
    N = len(x)
    L = []
    for k in range(1, kmax + 1):
        Lk = []
        for m in range(1, k + 1):
            # Number of intervals
            idx = np.arange(m - 1, N, k)
            n_m = len(idx) - 1
            if n_m < 1:
                continue
            Lmk = np.sum(np.abs(np.diff(x[idx]))) * (N - 1) / (n_m * k)
            Lk.append(Lmk)
        if Lk:
            L.append((k, np.mean(Lk)))
    if len(L) < 2:
        return 0.0
    log_k = np.log(np.array([v[0] for v in L]))
    log_L = np.log(np.array([v[1] for v in L]) + 1e-12)
    return float(-np.polyfit(log_k, log_L, 1)[0])

# ── Katz Fractal Dimension ───────────────────────────────────
def _katz_fd(x: np.ndarray) -> float:
    """Katz Fractal Dimension."""
    diffs = np.abs(np.diff(x))
    L = np.sum(diffs)                      # Total length of the curve
    d = np.max(np.abs(x - x[0]))          # Max distance from first point
    n = len(x) - 1
    if d == 0 or n == 0 or L == 0:
        return 0.0
    return float(np.log10(n) / (np.log10(n) + np.log10(d / L)))

# ── Petrosian Fractal Dimension ──────────────────────────────
def _petrosian_fd(x: np.ndarray) -> float:
    """Petrosian Fractal Dimension."""
    N = len(x)
    d = np.diff(x)
    Ndelta = np.sum(d[1:] * d[:-1] < 0)   # Number of sign changes in derivative
    return float(np.log10(N) / (np.log10(N) + np.log10(N / (N + 0.4 * Ndelta))))

# ── Hjorth Parameters ────────────────────────────────────────
def _hjorth(x: np.ndarray) -> Tuple[float, float, float]:
    """Hjorth Activity, Mobility, Complexity."""
    activity = float(np.var(x))
    d1 = np.diff(x)
    mobility = float(np.sqrt(np.var(d1) / activity)) if activity > 0 else 0.0
    d2 = np.diff(d1)
    mob2 = float(np.sqrt(np.var(d2) / np.var(d1))) if np.var(d1) > 0 else 0.0
    complexity = float(mob2 / mobility) if mobility > 0 else 0.0
    return activity, mobility, complexity


def extract_nonlinear_features(data: np.ndarray, fs: int = 128) -> Dict[str, float]:
    """13 nonlinear features averaged across channels.

    Includes: ApEn, PermEn, SpectralEntropy, SVDEntropy, LZC,
              Hurst, Lyapunov, HiguchiFD, KatzFD, PetrosianFD,
              Hjorth Activity/Mobility/Complexity.
    """
    accs = {
        # 'ApEn': [], 'PermEn': [],
        'HiguchiFD': [], 'KatzFD': [], 'PetrosianFD': [],
        'HjorthActivity': [], 'HjorthMobility': [], 'HjorthComplexity': [],
    }

    for ch in range(data.shape[1]):
        x = data[:, ch].astype(float)

        # # Approximate Entropy
        # accs['ApEn'].append(_apen(x))

        # # Permutation Entropy
        # accs['PermEn'].append(_perm_entropy(x))

        # Higuchi FD
        accs['HiguchiFD'].append(_higuchi_fd(x))

        # Katz FD
        accs['KatzFD'].append(_katz_fd(x))

        # Petrosian FD
        accs['PetrosianFD'].append(_petrosian_fd(x))

        # Hjorth
        act, mob, comp = _hjorth(x)
        accs['HjorthActivity'].append(act)
        accs['HjorthMobility'].append(mob)
        accs['HjorthComplexity'].append(comp)

    return {f'nonlinear_{k}': float(np.mean(v)) for k, v in accs.items()}

def extract_all_features(data: np.ndarray, fs: int = 128) -> Dict[str, float]:
    """Extract all 52 features from data."""
    # Data already filtered by CH_INDICES before calling this
    features = {}
    features.update(extract_time_features(data))
    features.update(extract_frequency_features(data, fs))
    features.update(extract_time_frequency_features(data, fs))
    features.update(extract_wavelet_features(data))
    features.update(extract_connectivity_features(data, fs))
    features.update(extract_nonlinear_features(data))
    return features

print("✓ Feature extraction functions defined (52 features)")

"""---
## STEP 4: Per-Channel Feature Extraction Function
### Extract individual channel values for selected features
"""

def extract_feature_per_channel(data: np.ndarray, feature_name: str, fs: int = 128) -> np.ndarray:
    """
    Extract one feature for each channel.

    Args:
        data: EEG data (samples, n_channels_work) - ALREADY FILTERED
        feature_name: Name of feature (e.g., 'time_RMS', 'freq_ALPHA_power')
        fs: Sampling frequency

    Returns:
        Array of values per channel (n_channels_work,)
    """
    n_ch = data.shape[1]
    values = np.zeros(n_ch)

    # TIME DOMAIN
    if feature_name.startswith('time_'):
        feat_type = feature_name.replace('time_', '')

        for ch in range(n_ch):
            ch_data = data[:, ch]

            if feat_type == 'MAV':
                values[ch] = np.mean(np.abs(ch_data))
            elif feat_type == 'RMS':
                values[ch] = np.sqrt(np.mean(ch_data ** 2))
            elif feat_type == 'STD':
                values[ch] = np.std(ch_data)
            elif feat_type == 'VAR':
                values[ch] = np.var(ch_data)
            elif feat_type == 'ZCR':
                values[ch] = np.sum(np.diff(np.sign(ch_data)) != 0)
            elif feat_type == 'KURT':
                from scipy.stats import kurtosis
                values[ch] = kurtosis(ch_data)
            elif feat_type == 'SKEW':
                from scipy.stats import skew
                values[ch] = skew(ch_data)
            elif feat_type == 'MEDIAN':
                values[ch] = np.median(ch_data)
            elif feat_type == 'PTP':
                values[ch] = np.ptp(ch_data)
            elif feat_type == 'ENERGY':
                values[ch] = np.sum(ch_data ** 2)
            elif feat_type == 'MIN':
                values[ch] = np.min(ch_data)
            elif feat_type == 'MAX':
                values[ch] = np.max(ch_data)
            elif feat_type == 'SAD':
                values[ch] = np.sum(np.abs(np.diff(ch_data)))

    # FREQUENCY DOMAIN
    elif feature_name.startswith('freq_'):
        for ch in range(n_ch):
            ch_data = data[:, ch]
            f, psd = welch(ch_data, fs=fs, nperseg=min(256, len(ch_data)))

            # Band selection
            if 'DELTA' in feature_name:
                idx = np.logical_and(f >= 1, f <= 4)
            elif 'THETA' in feature_name:
                idx = np.logical_and(f >= 4, f <= 8)
            elif 'ALPHA' in feature_name:
                idx = np.logical_and(f >= 8, f <= 13)
            elif 'BETA' in feature_name:
                idx = np.logical_and(f >= 13, f <= 30)
            elif 'GAMMA' in feature_name:
                idx = np.logical_and(f >= 30, f <= 50)
            elif 'TOTAL' in feature_name:
                idx = f >= 1

            # Compute metric
            if '_rel' in feature_name:
                total_power = np.trapz(psd[f >= 1], f[f >= 1])
                band_power = np.trapz(psd[idx], f[idx])
                values[ch] = band_power / total_power if total_power > 0 else 0
            elif '_power' in feature_name:
                values[ch] = np.trapz(psd[idx], f[idx])
            elif 'peak_freq' in feature_name:
                values[ch] = f[np.argmax(psd)]
            elif 'mean_freq' in feature_name:
                values[ch] = np.sum(f * psd) / np.sum(psd)
            elif 'median_freq' in feature_name:
                cum = np.cumsum(psd)
                values[ch] = f[np.where(cum >= cum[-1]/2)[0][0]]
            elif 'spectral_spread' in feature_name:
                mf = np.sum(f * psd) / np.sum(psd)
                values[ch] = np.sqrt(np.sum(((f - mf)**2) * psd) / np.sum(psd))
            elif 'theta_alpha_ratio' in feature_name:
                theta_idx = np.logical_and(f >= 4, f <= 8)
                alpha_idx = np.logical_and(f >= 8, f <= 13)
                theta_p = np.trapz(psd[theta_idx], f[theta_idx])
                alpha_p = np.trapz(psd[alpha_idx], f[alpha_idx])
                values[ch] = theta_p / alpha_p if alpha_p > 0 else 0

    # TIME-FREQUENCY
    elif feature_name.startswith('tf_'):
        for ch in range(n_ch):
            _, _, Zxx = signal.stft(data[:, ch], fs=fs, nperseg=256, noverlap=128)
            S = np.abs(Zxx) ** 2

            if 'stft_energy' in feature_name:
                values[ch] = np.sum(S)
            elif 'entropy' in feature_name:
                S_norm = S / (np.sum(S) + 1e-12)
                values[ch] = -np.sum(S_norm * np.log(S_norm + 1e-12))

    # WAVELET
    elif feature_name.startswith('wavelet_'):
        for ch in range(n_ch):
            coeffs = pywt.wavedec(data[:, ch], 'db4', level=4)

            if 'energy_L' in feature_name:
                level = int(feature_name.split('_L')[-1])
                values[ch] = np.sum(coeffs[level] ** 2)
            elif 'total_energy' in feature_name:
                values[ch] = sum(np.sum(c**2) for c in coeffs)
            elif 'mean_entropy' in feature_name:
                ents = []
                for c in coeffs:
                    if len(c) > 0:
                        p = np.abs(c) / (np.sum(np.abs(c)) + 1e-10)
                        ents.append(entropy(p + 1e-10))
                values[ch] = np.mean(ents)

    # NONLINEAR
    elif feature_name.startswith('nonlinear_'):
        ft = feature_name[len('nonlinear_'):]
        for ch in range(n_ch):
            x = data[:, ch].astype(float)
            # if   ft == 'ApEn'              : values[ch] = _apen(x)
            # elif ft == 'PermEn'            : values[ch] = _perm_entropy(x)
            if ft == 'HiguchiFD'        : values[ch] = _higuchi_fd(x)
            elif ft == 'KatzFD'           : values[ch] = _katz_fd(x)
            elif ft == 'PetrosianFD'      : values[ch] = _petrosian_fd(x)
            elif ft == 'HjorthActivity'   : values[ch] = float(np.var(x))
            elif ft == 'HjorthMobility'   :
                act = np.var(x)
                d1  = np.diff(x)
                values[ch] = float(np.sqrt(np.var(d1) / act)) if act > 0 else 0.0
            elif ft == 'HjorthComplexity' :
                act = np.var(x); d1 = np.diff(x); d2 = np.diff(d1)
                mob = float(np.sqrt(np.var(d1) / act)) if act > 0 else 0.0
                mob2 = float(np.sqrt(np.var(d2) / np.var(d1))) if np.var(d1) > 0 else 0.0
                values[ch] = float(mob2 / mob) if mob > 0 else 0.0


    # CONNECTIVITY (compute average connectivity per channel)
    elif feature_name.startswith('conn_'):
        conn_matrix = np.zeros((n_ch, n_ch))

        if 'diff_entropy' in feature_name:
            # Per-channel metric
            for ch in range(n_ch):
                var = np.var(data[:, ch])
                values[ch] = 0.5 * np.log(2 * np.pi * np.e * var) if var > 0 else 0

        else:  # PLV, PLI, wPLI
            phases = np.angle(hilbert(data, axis=0))

            for i in range(n_ch):
                for j in range(i+1, n_ch):
                    phase_diff = phases[:, i] - phases[:, j]

                    if 'plv' in feature_name:
                        val = np.abs(np.mean(np.exp(1j * phase_diff)))
                    elif 'pli' in feature_name and 'wpli' not in feature_name:
                        val = np.abs(np.mean(np.sign(np.sin(phase_diff))))
                    elif 'wpli' in feature_name:
                        imag = np.imag(np.exp(1j * phase_diff))
                        denom = np.mean(np.abs(imag))
                        val = np.abs(np.mean(imag)) / denom if denom > 0 else 0
                    else:
                        val = 0

                    conn_matrix[i, j] = val
                    conn_matrix[j, i] = val

            # Average per channel
            for ch in range(n_ch):
                other_chs = np.delete(conn_matrix[ch, :], ch)
                values[ch] = np.mean(other_chs)

    return values

print("✓ Per-channel extraction function defined")

"""---
## WORKFLOW EXECUTION
---

### ▶️ STEP 1: Extract Features from All Files
"""

print("="*80)
print("STEP 1: FEATURE EXTRACTION")
print("="*80)

# Load files and scales
files = get_all_files(DIR_FILTERED)
scales_df = load_scales(SCALES_FILE)
files = [
    f for f in files
    if parse_filename(f) is not None and parse_filename(f)['task'] in TASKS
]

print(f"\n  Found {len(files)} files")  # akan menampilkan 360

print(f"\n📁 Found {len(files)} files")
print(f"📊 Extracting 52 features per file")
print(f"🔬 Using {N_CHANNELS_WORK}/{N_CHANNELS} channels\n")

# Extract features from all files
results = []

for filepath in tqdm(files, desc="Extracting features"):
    file_info = parse_filename(filepath)
    if file_info is None:
        continue
    if file_info['task'] not in TASKS:   # <-- tambahkan ini
        continue

    # Load and filter data to working channels only
    data_full = load_eeg_file(filepath)
    data = data_full[:, CH_INDICES]  # Filter to working channels

    # Extract features
    features = extract_all_features(data, fs=FS)

    # Get stress label
    stress_label = get_stress_label(
        file_info['task'],
        file_info['subject'],
        file_info['trial'],
        scales_df
    )

    # Combine
    row = {
        **file_info,
        **features,
        'stress_label': stress_label
    }
    results.append(row)

# Create DataFrame
features_df = pd.DataFrame(results)

print(f"\n✓ Feature extraction complete")
print(f"   Shape: {features_df.shape}")
print(f"   Features: {len([c for c in features_df.columns if c not in ['file_id', 'task', 'subject', 'trial', 'stress_label']])}")
print(f"   Samples: {len(features_df)}")

# Save
output_file = os.path.join(DIR_OUTPUT, 'features_all.csv')
features_df.to_csv(output_file, index=False)
print(f"\n💾 Saved: {output_file}")

"""### ▶️ STEP 2: Correlation Analysis"""

print("\n" + "="*80)
print("STEP 2: CORRELATION ANALYSIS")
print("="*80)

# Get feature columns
feature_cols = [c for c in features_df.columns
                if c not in ['file_id', 'task', 'subject', 'trial', 'stress_label']]

print(f"\n📊 Computing correlations for {len(feature_cols)} features\n")

# Compute correlations
correlations = []

for feat in feature_cols:
    # Remove NaN values
    mask = ~(features_df[feat].isna() | features_df['stress_label'].isna())

    if mask.sum() < 10:  # Need at least 10 valid samples
        continue

    r, p = pearsonr(features_df.loc[mask, feat], features_df.loc[mask, 'stress_label'])

    correlations.append({
        'feature': feat,
        'correlation': r,
        'abs_correlation': abs(r),
        'p_value': p,
        'n_samples': mask.sum()
    })

# Create DataFrame
if len(correlations) == 0:
    print("\n❌ ERROR: No valid correlations computed!")
    print("   Possible causes:")
    print("   1. Stress labels are all NaN (check scales file loading)")
    print("   2. Feature values are all NaN")
    print("   3. Column names don't match")
    print("\n   → Check the output from scales loading above")
    print("   → Verify TASK_MAP matches your scales file column names")
    raise ValueError("Cannot proceed without valid correlations")

corr_df = pd.DataFrame(correlations)
corr_df = corr_df.sort_values('abs_correlation', ascending=False).reset_index(drop=True)

print("\n✓ Correlation analysis complete")
print(f"   Features analyzed: {len(corr_df)}")
print(f"   Correlation range: [{corr_df['correlation'].min():.3f}, {corr_df['correlation'].max():.3f}]")

# Save
corr_file = os.path.join(DIR_OUTPUT, 'correlations.csv')
corr_df.to_csv(corr_file, index=False)
print(f"\n💾 Saved: {corr_file}")

"""### ▶️ STEP 3: Select Top 5 Highest & Bottom 5 Weakest"""

print("\n" + "="*80)
print("STEP 3: FEATURE SELECTION")
print("="*80)

# Top 5 highest (by absolute correlation)
top_5_high = corr_df.head(5)['feature'].tolist()

# Bottom 5 weakest (smallest absolute correlation)
top_5_low = corr_df.tail(5)['feature'].tolist()

print("\n🔝 TOP 5 HIGHEST CORRELATION:")
print("-" * 60)
for i, feat in enumerate(top_5_high, 1):
    row = corr_df[corr_df['feature'] == feat].iloc[0]
    print(f"  {i}. {feat:<30} r = {row['correlation']:>7.4f}  (p = {row['p_value']:.4f})")

print("\n🔻 BOTTOM 5 WEAKEST CORRELATION:")
print("-" * 60)
for i, feat in enumerate(top_5_low, 1):
    row = corr_df[corr_df['feature'] == feat].iloc[0]
    print(f"  {i}. {feat:<30} r = {row['correlation']:>7.4f}  (p = {row['p_value']:.4f})")

# Combine for processing
selected_features = {
    'high': top_5_high,
    'low': top_5_low
}

print(f"\n✓ Selected 10 features (5 high + 5 low)")

"""### ▶️ STEP 4: Extract Per-Channel Values"""

print("\n" + "="*80)
print("STEP 4: PER-CHANNEL EXTRACTION")
print("="*80)

# Collect ALL feature names from the feature_cols list (derived in Step 2)
all_feature_names = feature_cols  # all features extracted in Step 1
files = [
    f for f in files
    if parse_filename(f) is not None and parse_filename(f)['task'] in TASKS
]

print(f"\n📊 Extracting per-channel values for ALL {len(all_feature_names)} features")
print(f"🔬 Channels: {N_CHANNELS_WORK}")
print(f"📁 Files: {len(files)}")
print(f"📐 Expected rows: {len(files)} files × {len(all_feature_names)} features = {len(files)*len(all_feature_names)}\n")

# Container for results
all_results = []

# Outer loop: files (load each file once per iteration)
print(f"\n  Found {len(files)} files")  # akan menampilkan 360
for filepath in tqdm(files, desc="Files"):
    file_info = parse_filename(filepath)
    if file_info is None:
        continue
    if file_info['task'] not in TASKS:   # <-- tambahkan ini
        continue

    # Load dan filter data SEKALI per file
    data_full = load_eeg_file(filepath)
    data = data_full[:, CH_INDICES]


    # Get stress label SEKALI per file
    stress_label = get_stress_label(
        file_info['task'],
        file_info['subject'],
        file_info['trial'],
        scales_df
    )

    # Inner loop: semua fitur → ekstrak per-channel untuk file ini
    for feature_name in all_feature_names:
        channel_values = extract_feature_per_channel(data, feature_name, fs=FS)

        row = {
            'file_id'      : file_info['file_id'],
            'task'         : file_info['task'],
            'subject'      : file_info['subject'],
            'trial'        : file_info['trial'],
            'feature_name' : feature_name,
            'stress_label' : stress_label,
        }

        # Tambahkan nilai per-channel (kolom = nama channel)
        for i, ch_name in enumerate(CHANNELS_WORK):
            row[ch_name] = float(channel_values[i])

        all_results.append(row)

# Build DataFrame
per_channel_df = pd.DataFrame(all_results)

n_files    = len(files)
n_features = len(all_feature_names)
print(f"\n✓ Per-channel extraction complete")
print(f"   Shape: {per_channel_df.shape}")
print(f"   Rows: {len(per_channel_df)} ({n_files} files × {n_features} features)")
print(f"   Columns: 6 metadata + {N_CHANNELS_WORK} channels")

# Save
per_ch_file = os.path.join(DIR_OUTPUT, 'per_channel_values.csv')
per_channel_df.to_csv(per_ch_file, index=False)
print(f"\n💾 Saved: {per_ch_file}")

"""### ▶️ STEP 5: Channel-Stress Correlation Analysis"""

print("\n" + "="*80)
print("STEP 5: CHANNEL-STRESS CORRELATION")
print("="*80)

print(f"\n📊 Computing per-channel correlations for ALL {len(all_feature_names)} features\n")

# Container for channel correlations
channel_corr_results = []

for feature_name in tqdm(all_feature_names, desc="Features"):
    feat_subset = per_channel_df[per_channel_df['feature_name'] == feature_name]

    for ch_name in CHANNELS_WORK:
        mask = ~(feat_subset[ch_name].isna() | feat_subset['stress_label'].isna())

        if mask.sum() < 10:
            continue

        r, p = pearsonr(
            feat_subset.loc[mask, ch_name],
            feat_subset.loc[mask, 'stress_label']
        )

        channel_corr_results.append({
            'feature_name'   : feature_name,
            'channel'        : ch_name,
            'correlation'    : r,
            'abs_correlation': abs(r),
            'p_value'        : p,
            'n_samples'      : int(mask.sum())
        })

# Create DataFrame, sorted by absolute correlation descending
channel_corr_df = (
    pd.DataFrame(channel_corr_results)
    .sort_values('abs_correlation', ascending=False)
    .reset_index(drop=True)
)

print("✓ Channel correlation analysis complete")
print(f"   Total correlations computed: {len(channel_corr_df)}")
print(f"   Features : {channel_corr_df['feature_name'].nunique()}")
print(f"   Channels : {channel_corr_df['channel'].nunique()}")
print(f"   Corr range: [{channel_corr_df['correlation'].min():.3f}, {channel_corr_df['correlation'].max():.3f}]")

print(f"\n🏆 Top 10 channel-feature pairs by |correlation|:")
print(f"   {'Feature':<35} {'Channel':<8} {'r':>8}  {'p':>8}")
print(f"   {'-'*35} {'-'*8} {'-'*8}  {'-'*8}")
for _, row in channel_corr_df.head(10).iterrows():
    print(f"   {row['feature_name']:<35} {row['channel']:<8} {row['correlation']:>8.4f}  {row['p_value']:>8.4f}")

# Save
ch_corr_file = os.path.join(DIR_OUTPUT, 'channel_correlations.csv')
channel_corr_df.to_csv(ch_corr_file, index=False)
print(f"\n💾 Saved: {ch_corr_file}")

"""### ▶️ STEP 6: Aggregate & Compare High vs Low"""

print("\n" + "="*80)
print("STEP 6: COMPARISON ANALYSIS (High vs Low)")
print("="*80)

# Aggregate: Average correlation per channel for each feature type
comparison_data = []

for ch_name in CHANNELS_WORK:
    # High correlation features
    high_data = channel_corr_df[
        (channel_corr_df['channel'] == ch_name) &
        (channel_corr_df['feature_type'] == 'high')
    ]
    avg_corr_high = high_data['abs_correlation'].mean()

    # Low correlation features
    low_data = channel_corr_df[
        (channel_corr_df['channel'] == ch_name) &
        (channel_corr_df['feature_type'] == 'low')
    ]
    avg_corr_low = low_data['abs_correlation'].mean()

    comparison_data.append({
        'channel': ch_name,
        'avg_corr_high': avg_corr_high,
        'avg_corr_low': avg_corr_low,
        'difference': avg_corr_high - avg_corr_low
    })

comparison_df = pd.DataFrame(comparison_data)
comparison_df = comparison_df.sort_values('avg_corr_high', ascending=False)

print("\n📊 CHANNEL RANKING (by High-Correlation Features)")
print("="*80)
print(f"{'Rank':<6} {'Channel':<10} {'Avg r (High)':<15} {'Avg r (Low)':<15} {'Difference':<12}")
print("-"*80)

for i, row in comparison_df.head(10).iterrows():
    rank = list(comparison_df.index).index(i) + 1
    print(f"{rank:<6} {row['channel']:<10} {row['avg_corr_high']:<15.4f} {row['avg_corr_low']:<15.4f} {row['difference']:<12.4f}")

print("\n✅ INTERPRETATION:")
print("-"*80)
top_ch = comparison_df.iloc[0]['channel']
top_high = comparison_df.iloc[0]['avg_corr_high']
top_low = comparison_df.iloc[0]['avg_corr_low']

print(f"  • Top channel: {top_ch}")
print(f"  • Correlation with high-corr features: {top_high:.4f}")
print(f"  • Correlation with low-corr features: {top_low:.4f}")
print(f"  • Difference: {top_high - top_low:.4f}")

if top_high > 2 * top_low:
    print(f"\n  ✓ High-correlation features show STRONG channel specificity")
    print(f"    → Channel {top_ch} is particularly informative for stress detection")
else:
    print(f"\n  ⚠ Moderate difference between high/low correlation features")
    print(f"    → Channel patterns less distinctive")

# Save
comp_file = os.path.join(DIR_OUTPUT, 'channel_comparison.csv')
comparison_df.to_csv(comp_file, index=False)
print(f"\n💾 Saved: {comp_file}")

print("\n" + "="*80)
print("✅ WORKFLOW COMPLETE")
print("="*80)
print("\nOutput files saved to:", DIR_OUTPUT)
print("  1. features_all.csv          - All features for all files")
print("  2. correlations.csv          - Feature-stress correlations")
print("  3. per_channel_values.csv    - Per-channel values (multi-index)")
print("  4. channel_correlations.csv  - Channel-stress correlations")
print("  5. channel_comparison.csv    - High vs Low comparison")
print("="*80)

# ── STANDALONE LOADER ──────────────────────────────────────
# Jalankan STEP 0 (imports) + STEP 1 (config) terlebih dahulu
# lalu jalankan cell ini untuk skip feature extraction

# ── Pilih konfigurasi channel ───────────────────────────────
CHANNEL_MODE = '24'  # ← GANTI: '24' atau '32'

DIR_OUTPUT_MAP = {
    '24': '/content/drive/MyDrive/SAM40/Data/Results/LAST/24ch',  # ← sesuaikan path
    '32': '/content/drive/MyDrive/Thesis',  # ← sesuaikan path
}

CHANNELS_WORK_MAP = {
    '24': [ch for ch in CHANNEL_NAMES if ch not in EXCLUDE_CHANNELS],  # exclude Fp1,Fp2,dst
    '32': CHANNEL_NAMES.copy(),
}

DIR_OUTPUT   = DIR_OUTPUT_MAP[CHANNEL_MODE]
CHANNELS_WORK = CHANNELS_WORK_MAP[CHANNEL_MODE]
N_CHANNELS_WORK = len(CHANNELS_WORK)
CH_INDICES   = [i for i, ch in enumerate(CHANNEL_NAMES) if ch in CHANNELS_WORK]

print(f"📂 Mode        : {CHANNEL_MODE} channels")
print(f"📁 Output dir  : {DIR_OUTPUT}")
print(f"🔬 Channels    : {N_CHANNELS_WORK} → {', '.join(CHANNELS_WORK)}")

# ── Load CSV dari Drive ─────────────────────────────────────
features_df     = pd.read_csv(os.path.join(DIR_OUTPUT, 'features_all.csv'))
corr_df         = pd.read_csv(os.path.join(DIR_OUTPUT, 'correlations.csv'))
per_channel_df  = pd.read_csv(os.path.join(DIR_OUTPUT, 'per_channel_values.csv'))
channel_corr_df = pd.read_csv(os.path.join(DIR_OUTPUT, 'channel_correlations.csv'))

# ── Rebuild variabel turunan ────────────────────────────────
feature_cols      = [c for c in features_df.columns
                     if c not in ['file_id', 'task', 'subject', 'trial', 'stress_label']]
all_feature_names = feature_cols

print(f"\n✓ Loaded from Drive ({CHANNEL_MODE}ch mode)")
print(f"   features_df     : {features_df.shape}")
print(f"   corr_df         : {corr_df.shape}")
print(f"   per_channel_df  : {per_channel_df.shape}")
print(f"   channel_corr_df : {channel_corr_df.shape}")
print(f"   feature_cols    : {len(feature_cols)} features")

from scipy.stats import spearmanr

print("\n" + "="*80)
print("STEP BONUS A: SPEARMAN CORRELATION — FEATURE vs BINARY STRESS")
print("="*80)

STRESS_THRESHOLD = 5  # > 5 → stress = 1

# Buat kolom binary stress label dari features_df
features_df['stress_binary'] = (features_df['stress_label'] > STRESS_THRESHOLD).astype(float)
features_df.loc[features_df['stress_label'].isna(), 'stress_binary'] = np.nan

n_stress    = int((features_df['stress_binary'] == 1).sum())
n_no_stress = int((features_df['stress_binary'] == 0).sum())
print(f"\n📊 Binary label distribution (threshold > {STRESS_THRESHOLD}):")
print(f"   Stress (1) : {n_stress} samples")
print(f"   No-stress (0): {n_no_stress} samples")
print(f"   Total valid  : {n_stress + n_no_stress} samples\n")

# Hitung Spearman untuk setiap fitur vs binary stress
spearman_feat_results = []

for feat in tqdm(feature_cols, desc="Spearman (features)"):
    mask = ~(features_df[feat].isna() | features_df['stress_binary'].isna())
    if mask.sum() < 10:
        continue

    rho, p = spearmanr(
        features_df.loc[mask, feat],
        features_df.loc[mask, 'stress_binary']
    )
    spearman_feat_results.append({
        'feature'        : feat,
        'spearman_rho'   : rho,
        'abs_rho'        : abs(rho),
        'p_value'        : p,
        'n_samples'      : int(mask.sum())
    })

spearman_feat_df = (
    pd.DataFrame(spearman_feat_results)
    .sort_values('abs_rho', ascending=False)
    .reset_index(drop=True)
)

print(f"✓ Spearman feature correlation complete")
print(f"   Features analyzed: {len(spearman_feat_df)}")
print(f"   ρ range: [{spearman_feat_df['spearman_rho'].min():.3f}, {spearman_feat_df['spearman_rho'].max():.3f}]")

print(f"\n🏆 Top 10 features by |ρ| (Spearman, binary stress):")
print(f"   {'Feature':<35} {'ρ':>8}  {'p':>8}")
print(f"   {'-'*35} {'-'*8}  {'-'*8}")
for _, row in spearman_feat_df.head(10).iterrows():
    print(f"   {row['feature']:<35} {row['spearman_rho']:>8.4f}  {row['p_value']:>8.4f}")

# ── Perbandingan Pearson vs Spearman ────────────────────────
print(f"\n📊 PEARSON vs SPEARMAN — Feature Ranking Comparison:")
print(f"   {'Feature':<35} {'Pearson r':>10} {'Spearman ρ':>11}  {'Δ|corr|':>8}")
print(f"   {'-'*35} {'-'*10} {'-'*11}  {'-'*8}")

# Merge kedua ranking (top 15 dari masing-masing)
top_pearson  = set(corr_df.head(15)['feature'].tolist())
top_spearman = set(spearman_feat_df.head(15)['feature'].tolist())
union_feats  = top_pearson | top_spearman

pearson_map  = corr_df.set_index('feature')['correlation'].to_dict()
spearman_map = spearman_feat_df.set_index('feature')['spearman_rho'].to_dict()

compare_rows = []
for f in union_feats:
    pr  = pearson_map.get(f, np.nan)
    sr  = spearman_map.get(f, np.nan)
    delta = abs(abs(sr) - abs(pr)) if not (np.isnan(pr) or np.isnan(sr)) else np.nan
    compare_rows.append({'feature': f, 'pearson_r': pr, 'spearman_rho': sr, 'delta_abs': delta})

compare_df = (
    pd.DataFrame(compare_rows)
    .sort_values('delta_abs', ascending=False)
    .reset_index(drop=True)
)
for _, row in compare_df.iterrows():
    print(f"   {row['feature']:<35} {row['pearson_r']:>10.4f} {row['spearman_rho']:>11.4f}  {row['delta_abs']:>8.4f}")

# Save
spearman_feat_file = os.path.join(DIR_OUTPUT, 'spearman_feature_binary.csv')
spearman_feat_df.to_csv(spearman_feat_file, index=False)
compare_file = os.path.join(DIR_OUTPUT, 'pearson_vs_spearman_features.csv')
compare_df.to_csv(compare_file, index=False)
print(f"\n💾 Saved: {spearman_feat_file}")
print(f"💾 Saved: {compare_file}")

print("\n" + "="*80)
print("STEP BONUS B: SPEARMAN CORRELATION — CHANNEL vs BINARY STRESS")
print("="*80)

# Tambahkan binary stress label ke per_channel_df
per_channel_df['stress_binary'] = (per_channel_df['stress_label'] > STRESS_THRESHOLD).astype(float)
per_channel_df.loc[per_channel_df['stress_label'].isna(), 'stress_binary'] = np.nan

print(f"\n📊 Computing Spearman per-channel × per-feature, lalu diagregasi...\n")

spearman_ch_results = []

for feature_name in tqdm(all_feature_names, desc="Spearman (channels)"):
    feat_subset = per_channel_df[per_channel_df['feature_name'] == feature_name]

    for ch_name in CHANNELS_WORK:
        mask = ~(feat_subset[ch_name].isna() | feat_subset['stress_binary'].isna())
        if mask.sum() < 10:
            continue

        rho, p = spearmanr(
            feat_subset.loc[mask, ch_name],
            feat_subset.loc[mask, 'stress_binary']
        )
        spearman_ch_results.append({
            'feature_name' : feature_name,
            'channel'      : ch_name,
            'spearman_rho' : rho,
            'abs_rho'      : abs(rho),
            'p_value'      : p,
            'n_samples'    : int(mask.sum())
        })

spearman_ch_df = (
    pd.DataFrame(spearman_ch_results)
    .sort_values('abs_rho', ascending=False)
    .reset_index(drop=True)
)

print(f"✓ Spearman channel correlation complete")
print(f"   Total pairs (feature × channel): {len(spearman_ch_df)}")

# ── Agregasi per channel: rata-rata |ρ| across all features ─
ch_agg_spearman = (
    spearman_ch_df
    .groupby('channel')['abs_rho']
    .agg(mean_abs_rho='mean', max_abs_rho='max', std_abs_rho='std')
    .sort_values('mean_abs_rho', ascending=False)
    .reset_index()
)

# Agregasi Pearson per channel (dari channel_corr_df) untuk perbandingan
ch_agg_pearson = (
    channel_corr_df
    .groupby('channel')['abs_correlation']
    .agg(mean_abs_r='mean', max_abs_r='max', std_abs_r='std')
    .sort_values('mean_abs_r', ascending=False)
    .reset_index()
)

# Merge untuk perbandingan
ch_compare_df = ch_agg_pearson.merge(ch_agg_spearman, on='channel')
ch_compare_df['delta_mean'] = abs(ch_compare_df['mean_abs_rho'] - ch_compare_df['mean_abs_r'])
ch_compare_df = ch_compare_df.sort_values('mean_abs_rho', ascending=False).reset_index(drop=True)
ch_compare_df['rank_pearson']  = ch_agg_pearson.set_index('channel')['mean_abs_r'].rank(ascending=False).reindex(ch_compare_df['channel']).values
ch_compare_df['rank_spearman'] = ch_compare_df['mean_abs_rho'].rank(ascending=False).astype(int)
ch_compare_df['rank_change']   = (ch_compare_df['rank_pearson'] - ch_compare_df['rank_spearman']).astype(int)

print(f"\n🏆 Channel Ranking — Pearson (continuous) vs Spearman (binary stress):")
print(f"   Agregasi = mean |corr| across ALL features per channel\n")
print(f"   {'Ch':<8} {'Rank P':>7} {'Rank S':>7} {'Δ Rank':>7}  {'Pearson r':>10} {'Spearman ρ':>11}")
print(f"   {'-'*8} {'-'*7} {'-'*7} {'-'*7}  {'-'*10} {'-'*11}")
for _, row in ch_compare_df.iterrows():
    delta_str = f"{row['rank_change']:+d}"
    marker = " ↑" if row['rank_change'] > 0 else (" ↓" if row['rank_change'] < 0 else "  ")
    print(f"   {row['channel']:<8} {int(row['rank_pearson']):>7} {row['rank_spearman']:>7} {delta_str:>7}{marker}"
          f"  {row['mean_abs_r']:>10.4f} {row['mean_abs_rho']:>11.4f}")

print(f"\n🏆 Top 10 channel-feature pairs by |ρ| (Spearman):")
print(f"   {'Feature':<35} {'Channel':<8} {'ρ':>8}  {'p':>8}")
print(f"   {'-'*35} {'-'*8} {'-'*8}  {'-'*8}")
for _, row in spearman_ch_df.head(10).iterrows():
    print(f"   {row['feature_name']:<35} {row['channel']:<8} {row['spearman_rho']:>8.4f}  {row['p_value']:>8.4f}")

# Save
spearman_ch_file  = os.path.join(DIR_OUTPUT, 'spearman_channel_binary.csv')
ch_compare_file   = os.path.join(DIR_OUTPUT, 'pearson_vs_spearman_channels.csv')
spearman_ch_df.to_csv(spearman_ch_file, index=False)
ch_compare_df.to_csv(ch_compare_file, index=False)
print(f"\n💾 Saved: {spearman_ch_file}")
print(f"💾 Saved: {ch_compare_file}")

print("\n" + "="*80)
print("STEP BONUS B: SPEARMAN CORRELATION — CHANNEL vs BINARY STRESS")
print("="*80)

# Tambahkan binary stress label ke per_channel_df
per_channel_df['stress_binary'] = (per_channel_df['stress_label'] > STRESS_THRESHOLD).astype(float)
per_channel_df.loc[per_channel_df['stress_label'].isna(), 'stress_binary'] = np.nan

print(f"\n📊 Computing Spearman per-channel × per-feature, lalu diagregasi...\n")

spearman_ch_results = []

for feature_name in tqdm(all_feature_names, desc="Spearman (channels)"):
    feat_subset = per_channel_df[per_channel_df['feature_name'] == feature_name]

    for ch_name in CHANNELS_WORK:
        mask = ~(feat_subset[ch_name].isna() | feat_subset['stress_binary'].isna())
        if mask.sum() < 10:
            continue

        rho, p = spearmanr(
            feat_subset.loc[mask, ch_name],
            feat_subset.loc[mask, 'stress_binary']
        )
        spearman_ch_results.append({
            'feature_name' : feature_name,
            'channel'      : ch_name,
            'spearman_rho' : rho,
            'abs_rho'      : abs(rho),
            'p_value'      : p,
            'n_samples'    : int(mask.sum())
        })

spearman_ch_df = (
    pd.DataFrame(spearman_ch_results)
    .sort_values('abs_rho', ascending=False)
    .reset_index(drop=True)
)

print(f"✓ Spearman channel correlation complete")
print(f"   Total pairs (feature × channel): {len(spearman_ch_df)}")

# ── Agregasi per channel: rata-rata |ρ| across all features ─
ch_agg_spearman = (
    spearman_ch_df
    .groupby('channel')['abs_rho']
    .agg(mean_abs_rho='mean', max_abs_rho='max', std_abs_rho='std')
    .sort_values('mean_abs_rho', ascending=False)
    .reset_index()
)

# Agregasi Pearson per channel (dari channel_corr_df) untuk perbandingan
ch_agg_pearson = (
    channel_corr_df
    .groupby('channel')['abs_correlation']
    .agg(mean_abs_r='mean', max_abs_r='max', std_abs_r='std')
    .sort_values('mean_abs_r', ascending=False)
    .reset_index()
)

# Merge untuk perbandingan
ch_compare_df = ch_agg_pearson.merge(ch_agg_spearman, on='channel')
ch_compare_df['delta_mean'] = abs(ch_compare_df['mean_abs_rho'] - ch_compare_df['mean_abs_r'])
ch_compare_df = ch_compare_df.sort_values('mean_abs_rho', ascending=False).reset_index(drop=True)
ch_compare_df['rank_pearson']  = ch_agg_pearson.set_index('channel')['mean_abs_r'].rank(ascending=False).reindex(ch_compare_df['channel']).values
ch_compare_df['rank_spearman'] = ch_compare_df['mean_abs_rho'].rank(ascending=False).astype(int)
ch_compare_df['rank_change']   = (ch_compare_df['rank_pearson'] - ch_compare_df['rank_spearman']).astype(int)

print(f"\n🏆 Channel Ranking — Pearson (continuous) vs Spearman (binary stress):")
print(f"   Agregasi = mean |corr| across ALL features per channel\n")
print(f"   {'Ch':<8} {'Rank P':>7} {'Rank S':>7} {'Δ Rank':>7}  {'Pearson r':>10} {'Spearman ρ':>11}")
print(f"   {'-'*8} {'-'*7} {'-'*7} {'-'*7}  {'-'*10} {'-'*11}")
for _, row in ch_compare_df.iterrows():
    delta_str = f"{row['rank_change']:+d}"
    marker = " ↑" if row['rank_change'] > 0 else (" ↓" if row['rank_change'] < 0 else "  ")
    print(f"   {row['channel']:<8} {int(row['rank_pearson']):>7} {row['rank_spearman']:>7} {delta_str:>7}{marker}"
          f"  {row['mean_abs_r']:>10.4f} {row['mean_abs_rho']:>11.4f}")

print(f"\n🏆 Top 10 channel-feature pairs by |ρ| (Spearman):")
print(f"   {'Feature':<35} {'Channel':<8} {'ρ':>8}  {'p':>8}")
print(f"   {'-'*35} {'-'*8} {'-'*8}  {'-'*8}")
for _, row in spearman_ch_df.head(10).iterrows():
    print(f"   {row['feature_name']:<35} {row['channel']:<8} {row['spearman_rho']:>8.4f}  {row['p_value']:>8.4f}")

# Save
spearman_ch_file  = os.path.join(DIR_OUTPUT, 'spearman_channel_binary.csv')
ch_compare_file   = os.path.join(DIR_OUTPUT, 'pearson_vs_spearman_channels.csv')
spearman_ch_df.to_csv(spearman_ch_file, index=False)
ch_compare_df.to_csv(ch_compare_file, index=False)
print(f"\n💾 Saved: {spearman_ch_file}")
print(f"💾 Saved: {ch_compare_file}")