# -*- coding: utf-8 -*-
"""HIGH_vs_LOW_Pearson_final (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1CtjRxq6OlLuj761UADhTl0J43vwSl1

# HIGH vs LOW Feature Correlation Classification (Pearson Correlation)

**Feature selection method:** Pearson Correlation ranking (per-fold, no leakage)

**Approach:**
- Rank **feature types** by avg |Pearson r| with **continuous stress label (1–10)** across ALL channels
- HIGH input = top-N feature types × ALL channels (32ch or 24ch)
- LOW input  = bottom-N feature types × ALL channels
- **Ranking uses continuous label (1–10); classifier uses binary label (0/1)**
- Channel significance is observed by comparing 32ch vs 24ch results within HIGH / LOW
- No channel selection or channel sweep — channel set is fixed per configuration

**Structure:**
1. Data Loading & Preprocessing
2. Reshape: Wide → Feature Matrix
3. Inter-Session 3-Fold Split
4. Feature Type Ranking via Pearson (per-fold, train only)
5. Model Definitions
6. Main Experiment Loop
7. Run Experiments
8. Results Aggregation
9. Confusion Matrix Visualization
10. N-Feature Sweep (1D)
11. Global vs Training Correlation Comparison
12. Key Analyses: HIGH vs LOW
13. 32ch vs 24ch Channel Comparison
14. Statistical Significance Tests
15. Feature Ranking Details Per Fold
16. Feature Ranking Stability
17. Final Conclusion
18. Save Report

## Setup
"""

import numpy as np
import pandas as pd
from pathlib import Path
from scipy.stats import pearsonr, spearmanr, wilcoxon, ttest_rel
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                              f1_score, confusion_matrix, ConfusionMatrixDisplay)
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

np.random.seed(42)
print('Libraries loaded successfully')

"""## Configuration"""

from google.colab import drive
drive.mount('/content/drive')

# ── Data paths ─────────────────────────────────────────────────────────────────
DATA_FILE_32CH = Path('/content/drive/MyDrive/SAM40/Data/Results/LAST/32ch/per_channel_values_32ch.csv')
DATA_FILE_24CH = Path('/content/drive/MyDrive/SAM40/Data/Results/LAST/24ch/per_channel_values_24ch.csv')
OUTPUT_DIR     = Path('/content/drive/MyDrive/SAM40/Data/Results/LAST/Final_Paper/Pearson')
OUTPUT_DIR.mkdir(exist_ok=True, parents=True)

# ── Global correlation files (computed on ALL data, outside this notebook) ─────
# correlations.csv  (32ch) / spearman_feature_binary.csv (24ch)
#   32ch cols: feature, correlation, abs_correlation, p_value, n_samples
#   24ch cols: feature, spearman_rho, abs_rho, p_value, n_samples
#   One row per feature type — avg |r| (Pearson) or |ρ| aggregated across all channels.
#
# channel_correlations.csv (32ch) / spearman_channel_binary.csv (24ch)
#   32ch cols: feature_name, channel, correlation, abs_correlation, p_value, n_samples
#   24ch cols: feature_name/feature, channel, spearman_rho/abs_rho, p_value, n_samples
#   One row per (channel, feature) pair.
GLOBAL_FEATURE_CSV_32CH = Path('/content/drive/MyDrive/SAM40/Data/Results/LAST/32ch/correlations.csv')
GLOBAL_FEATURE_CSV_24CH = Path('/content/drive/MyDrive/SAM40/Data/Results/LAST/24ch/spearman_feature_binary.csv')
GLOBAL_CHANNEL_CSV_32CH = Path('/content/drive/MyDrive/SAM40/Data/Results/LAST/32ch/channel_correlations.csv')
GLOBAL_CHANNEL_CSV_24CH = Path('/content/drive/MyDrive/SAM40/Data/Results/LAST/24ch/spearman_channel_binary.csv')

# ── Enable/disable experiments ──────────────────────────────────────────────────
RUN_32CH = True
RUN_24CH = False   # Set True when 24ch data is available

# ── Channel configurations ──────────────────────────────────────────────────────
ALL_CHANNELS_32 = [
    'CZ','FZ','Fp1','F7','F3','FC1','C3','FC5',
    'FT9','T7','CP5','CP1','P3','P7','PO9','O1',
    'PZ','OZ','O2','PO10','P8','P4','CP2','CP6',
    'T8','FT10','FC6','C4','FC2','F4','F8','Fp2']

EXCLUDE_CHANNELS = ['Fp1','Fp2','F7','F8','FT9','FT10','PO9','PO10']
CHANNELS_24      = [ch for ch in ALL_CHANNELS_32 if ch not in EXCLUDE_CHANNELS]

# ── Parameters ──────────────────────────────────────────────────────────────────
STRESS_THRESHOLD  = 5        # > 5 stress (1), else non-stress (0) — for classifier
# NOTE: Pearson ranking uses continuous stress_label (1–10), NOT stress_binary
N_TOP_FEATURES    = 5        # default top feature types (main experiment)
N_BOTTOM_FEATURES = 5        # default bottom feature types
RANDOM_STATE      = 42
MAJORITY_BASELINE = 233 / 360  # ~0.647

# ── N-Feature Sweep ─────────────────────────────────────────────────────────────
# Sweeps number of feature types selected.
# Input columns = n_feat × len(ALL_CHANNELS) per config.
N_FEATURE_SWEEP = [3, 5, 10, 15, 20]

print('Configuration:')
print(f'  32ch: {len(ALL_CHANNELS_32)} channels,  Run={RUN_32CH}')
print(f'  24ch: {len(CHANNELS_24)} channels,  Run={RUN_24CH}')
print(f'  Excluded: {EXCLUDE_CHANNELS}')
print(f'  Default N_top={N_TOP_FEATURES}, N_bottom={N_BOTTOM_FEATURES}')
print(f'  Feature sweep : {N_FEATURE_SWEEP}')
print(f'  Input size example (32ch): {N_TOP_FEATURES} feat × {len(ALL_CHANNELS_32)} ch'
      f' = {N_TOP_FEATURES * len(ALL_CHANNELS_32)} columns')
print(f'  Majority baseline: {MAJORITY_BASELINE:.4f}')

"""## 1. Data Loading & Preprocessing"""

datasets = {}

def load_dataset(path, channels, label):
    df = pd.read_csv(path)
    print(f'  Loaded {label}: {len(df)} rows')
    print(f'  Columns (first 8): {list(df.columns[:8])}')
    print(f'  Unique file_ids  : {df["file_id"].nunique()}')
    print(f'  Unique features  : {df["feature_name"].nunique()}')

    expected = set(channels)
    actual   = set(df.columns) - {'file_id','task','subject','trial','feature_name','stress_label'}
    if expected != actual:
        miss  = expected - actual
        extra = actual - expected
        print(f'  WARNING — channel mismatch! missing={miss}, extra={extra}')
    else:
        print(f'  Channel check: OK ({len(expected)} channels)')

    print(f'  Missing values: {df.isnull().sum().sum()}')
    df['stress_binary'] = (df['stress_label'] > STRESS_THRESHOLD).astype(int)
    dist = df.groupby('file_id')['stress_binary'].first().value_counts()
    print(f'  Non-stress: {dist.get(0,0)}, Stress: {dist.get(1,0)}, '
          f'Ratio: {dist.get(0,0)/max(dist.get(1,0),1):.2f}:1')
    return df

print('='*80)
print('DATA LOADING')
print('='*80)

if RUN_32CH:
    print('\n32-channel:')
    datasets['32ch'] = load_dataset(DATA_FILE_32CH, ALL_CHANNELS_32, '32ch')

if RUN_24CH:
    print('\n24-channel:')
    datasets['24ch'] = load_dataset(DATA_FILE_24CH, CHANNELS_24, '24ch')

print(f'\nLoaded: {list(datasets.keys())}')

"""## 2. Reshape Data: Wide → Feature Matrix

Columns: `{feature_type}_{channel}` — e.g. `delta_psd_CZ`, `alpha_mean_F3`

"""

def create_feature_matrix(df, channels, config_name):
    print(f'\nCreating feature matrix for {config_name}...')
    files    = df[['file_id','subject','trial','stress_binary','stress_label']].drop_duplicates().reset_index(drop=True)
    features = sorted(df['feature_name'].unique())   # sorted → deterministic order
    print(f'  Samples        : {len(files)}')
    print(f'  Feature types  : {len(features)}')
    print(f'  Channels       : {len(channels)}')

    feature_data = {}
    for feat in features:
        feat_df = df[df['feature_name'] == feat].set_index('file_id')
        for ch in channels:
            if ch in feat_df.columns:
                feature_data[f'{feat}_{ch}'] = feat_df[ch]

    feat_matrix = pd.DataFrame(feature_data)
    result      = files.merge(feat_matrix, left_on='file_id', right_index=True, how='left')
    feat_cols   = [c for c in result.columns if c not in ['file_id','subject','trial','stress_binary','stress_label']]

    miss = result[feat_cols].isnull().sum().sum()
    if miss > 0:
        print(f'  Warning: {miss} missing values — filling with column mean')
        result[feat_cols] = result[feat_cols].fillna(result[feat_cols].mean())

    print(f'  Result shape   : {result.shape}  ({len(feat_cols)} feature×channel columns)')
    return result, feat_cols, features, list(channels)

feature_matrices = {}
feature_columns  = {}
feature_types    = {}
channel_lists    = {}

print('='*80)
print('CREATING FEATURE MATRICES')
print('='*80)

if '32ch' in datasets:
    fm, fc, ft, cl = create_feature_matrix(datasets['32ch'], ALL_CHANNELS_32, '32ch')
    feature_matrices['32ch'] = fm
    feature_columns['32ch']  = fc
    feature_types['32ch']    = ft
    channel_lists['32ch']    = cl

if '24ch' in datasets:
    fm, fc, ft, cl = create_feature_matrix(datasets['24ch'], CHANNELS_24, '24ch')
    feature_matrices['24ch'] = fm
    feature_columns['24ch']  = fc
    feature_types['24ch']    = ft
    channel_lists['24ch']    = cl

print(f'\nMatrices ready: {list(feature_matrices.keys())}')

"""## 3. Inter-Session 3-Fold Split"""

def create_inter_session_folds(data, config_name):
    """
    Fold k: test=trial_k, train=remaining trials.
    3 folds total (one per trial).
    """
    folds = []
    for test_trial in [1, 2, 3]:
        test_idx  = data[data['trial'] == test_trial].index
        train_idx = data[data['trial'] != test_trial].index
        folds.append({
            'fold'        : test_trial,
            'train_idx'   : train_idx,
            'test_idx'    : test_idx,
            'test_trial'  : test_trial,
            'train_trials': [t for t in [1,2,3] if t != test_trial]
        })
    return folds

folds_dict = {}
print('='*80)
print('INTER-SESSION FOLDS')
print('='*80)

for config in feature_matrices.keys():
    folds = create_inter_session_folds(feature_matrices[config], config)
    folds_dict[config] = folds
    for fold in folds:
        print(f'  {config} Fold {fold["fold"]}: '
              f'train={len(fold["train_idx"])} samples (trials {fold["train_trials"]}), '
              f'test={len(fold["test_idx"])} samples (trial {fold["test_trial"]})')

"""## 4. Feature Type Ranking via Pearson Correlation (Per-Fold, No Leakage)

For each feature type (e.g. `delta_psd`), compute Pearson r between every `feat_type_{ch}` column  
and the binary stress label on **scaled training data only**, then average the |r| values across all  
channels to get a single score per feature type.

**Selection:**
- HIGH = top-N feature types × ALL channels → N × n_ch columns
- LOW  = bottom-N feature types × ALL channels → N × n_ch columns
- HIGH+LOW = union of both

No leakage: correlation computed on training data only (fit scaler on train).

"""

def rank_feature_types_by_pearson(X_train_sc, y_train, feat_types, channels):
    """
    Rank feature types by avg |Pearson r| across all channels.

    For each feature type ft:
      For each channel ch:
        Compute pearsonr(X_train_sc['{ft}_{ch}'], y_train) → r
      avg_abs_r(ft) = mean(|r| across channels)

    Returns:
        ranked : list of (feat_type, avg_abs_r, per_ch_r_dict) — sorted desc by avg_abs_r
        col_rho: dict { col_name : (r, abs_r, p) } for all individual columns
    """
    col_rho = {}
    for col in X_train_sc.columns:
        try:
            rho, p      = pearsonr(X_train_sc[col], y_train)
            col_rho[col] = (float(rho), abs(float(rho)), float(p))
        except Exception:
            col_rho[col] = (0.0, 0.0, 1.0)

    ranked = []
    for ft in feat_types:
        per_ch = {}
        abs_vals = []
        for ch in channels:
            col = f'{ft}_{ch}'
            if col in col_rho:
                per_ch[ch] = col_rho[col][0]
                abs_vals.append(col_rho[col][1])
        avg = float(np.mean(abs_vals)) if abs_vals else 0.0
        ranked.append((ft, avg, per_ch))

    ranked.sort(key=lambda x: x[1], reverse=True)
    return ranked, col_rho


def select_feature_sets(ranked, channels, n_top, n_bottom):
    """
    Build HIGH and LOW column sets.

    HIGH = top-n_top feature types × ALL channels
    LOW  = bottom-n_bottom feature types × ALL channels

    Returns:
        high_cols  : list[str]  (column names)
        low_cols   : list[str]
        high_feats : list[str]  (feature type names)
        low_feats  : list[str]
    """
    total = len(ranked)
    n_top    = min(n_top,    total // 2) or 1
    n_bottom = min(n_bottom, total // 2) or 1

    high_feats = [ft for ft, _, _ in ranked[:n_top]]
    low_feats  = [ft for ft, _, _ in ranked[-n_bottom:]]

    high_cols = [f'{ft}_{ch}' for ft in high_feats for ch in channels]
    low_cols  = [f'{ft}_{ch}' for ft in low_feats  for ch in channels]

    return high_cols, low_cols, high_feats, low_feats


# ── Sanity check on Fold 1 ──────────────────────────────────────────────────────
test_cfg  = list(feature_matrices.keys())[0]
fold_test = folds_dict[test_cfg][0]

X_tr_full = feature_matrices[test_cfg].loc[fold_test['train_idx'], feature_columns[test_cfg]]
y_tr_binary = feature_matrices[test_cfg].loc[fold_test['train_idx'], 'stress_binary']
y_tr_cont   = feature_matrices[test_cfg].loc[fold_test['train_idx'], 'stress_label']  # continuous for ranking
sc_test     = StandardScaler()
X_tr_sc     = pd.DataFrame(sc_test.fit_transform(X_tr_full),
                            columns=feature_columns[test_cfg], index=fold_test['train_idx'])

ranked_test, _ = rank_feature_types_by_pearson(
    X_tr_sc, y_tr_cont, feature_types[test_cfg], channel_lists[test_cfg])

high_c, low_c, hf, lf = select_feature_sets(
    ranked_test, channel_lists[test_cfg], N_TOP_FEATURES, N_BOTTOM_FEATURES)

print(f'Sanity check — {test_cfg} Fold 1:')
print(f'  Feature types total : {len(ranked_test)}')
print(f'  Channels            : {len(channel_lists[test_cfg])}')
print(f'\nTOP {N_TOP_FEATURES} feature types (HIGH) — sorted by avg |Pearson r|:')
for i, (ft, avg, _) in enumerate(ranked_test[:N_TOP_FEATURES], 1):
    print(f'  {i}. {ft:<35}  avg|r| = {avg:.6f}')
print(f'\nBOTTOM {N_BOTTOM_FEATURES} feature types (LOW) — lowest avg |Pearson r|:')
total_ft = len(ranked_test)
for i, (ft, avg, _) in enumerate(ranked_test[-N_BOTTOM_FEATURES:], total_ft - N_BOTTOM_FEATURES + 1):
    print(f'  {i}. {ft:<35}  avg|r| = {avg:.6f}')
print(f'\nHIGH columns: {len(high_c)}'
      f'  ({N_TOP_FEATURES} feat × {len(channel_lists[test_cfg])} ch)')
print(f'LOW  columns: {len(low_c)}'
      f'  ({N_BOTTOM_FEATURES} feat × {len(channel_lists[test_cfg])} ch)')

"""## 5. Model Definitions"""

def get_models():
    return {
        'LogReg': LogisticRegression(class_weight='balanced', max_iter=500,
                                      random_state=RANDOM_STATE),
        'SVM'   : SVC(kernel='linear', class_weight='balanced',
                      random_state=RANDOM_STATE),
        'RF'    : RandomForestClassifier(n_estimators=200, max_depth=10,
                                          min_samples_leaf=5,
                                          class_weight='balanced',
                                          random_state=RANDOM_STATE),
        'KNN'   : KNeighborsClassifier(n_neighbors=5)
    }

print('Models:', list(get_models().keys()))

"""## 6. Main Experiment Loop

Per fold:
1. Scale training data (fit on train only, no leakage)
2. Rank feature types by avg |Spearman ρ| across all channels (on training data only)
3. HIGH = top-N feat types × ALL channels; LOW = bottom-N × ALL channels
4. Feature sets evaluated: HIGH, LOW, HIGH+LOW
5. Train 4 classifiers → accuracy, precision, recall, F1, confusion matrix

"""

def run_experiment(data, folds, feature_cols, feat_types, channels, channel_config='32ch'):
    results          = []
    feature_rankings = []
    confusion_mats   = {}
    models           = get_models()

    for fold_info in folds:
        fold_num  = fold_info['fold']
        train_idx = fold_info['train_idx']
        test_idx  = fold_info['test_idx']

        print(f'\n  Fold {fold_num} (test=trial{fold_info["test_trial"]})', end='')

        X_train_full   = data.loc[train_idx, feature_cols]
        y_train        = data.loc[train_idx, 'stress_binary']   # for model training & evaluation
        y_train_cont   = data.loc[train_idx, 'stress_label']    # for Pearson ranking (continuous 1–10)
        X_test_full    = data.loc[test_idx,  feature_cols]
        y_test         = data.loc[test_idx,  'stress_binary']

        # ── Scale (fit on train only) ──────────────────────────────────────
        scaler     = StandardScaler()
        X_train_sc = pd.DataFrame(scaler.fit_transform(X_train_full),
                                   columns=feature_cols, index=train_idx)
        X_test_sc  = pd.DataFrame(scaler.transform(X_test_full),
                                   columns=feature_cols, index=test_idx)

        # ── Pearson ranking on training data (continuous label 1–10) ───────
        ranked, col_rho = rank_feature_types_by_pearson(
            X_train_sc, y_train_cont, feat_types, channels)

        high_cols, low_cols, high_feats, low_feats = select_feature_sets(
            ranked, channels, N_TOP_FEATURES, N_BOTTOM_FEATURES)

        feature_rankings.append({
            'fold'      : fold_num,
            'ranked'    : ranked,
            'col_rho'   : col_rho,
            'high_feats': high_feats,
            'low_feats' : low_feats,
            'high_cols' : high_cols,
            'low_cols'  : low_cols,
        })

        print(f'  |  HIGH: {high_feats}')
        print(f'           LOW:  {low_feats}')

        # ── Feature sets ───────────────────────────────────────────────────
        combined_cols = list(dict.fromkeys(high_cols + low_cols))
        feature_sets  = {
            'HIGH'    : high_cols,
            'LOW'     : low_cols,
            'HIGH+LOW': combined_cols
        }

        for feat_set_name, selected in feature_sets.items():
            selected = [c for c in selected if c in X_train_sc.columns]
            X_tr     = X_train_sc[selected]
            X_te     = X_test_sc[selected]

            for model_name, model in models.items():
                model.fit(X_tr, y_train)
                y_pred = model.predict(X_te)
                cm     = confusion_matrix(y_test, y_pred)
                confusion_mats[(fold_num, feat_set_name, model_name)] = cm

                results.append({
                    'channel_config': channel_config,
                    'n_channels'    : len(channels),
                    'fold'          : fold_num,
                    'test_trial'    : fold_info['test_trial'],
                    'feature_set'   : feat_set_name,
                    'n_feat_types'  : (N_TOP_FEATURES if feat_set_name == 'HIGH'
                                       else N_BOTTOM_FEATURES if feat_set_name == 'LOW'
                                       else N_TOP_FEATURES + N_BOTTOM_FEATURES),
                    'n_columns'     : len(selected),
                    'model'         : model_name,
                    'accuracy'      : accuracy_score(y_test, y_pred),
                    'precision'     : precision_score(y_test, y_pred, zero_division=0),
                    'recall'        : recall_score(y_test, y_pred, zero_division=0),
                    'f1'            : f1_score(y_test, y_pred, zero_division=0),
                    'tn': cm[0,0], 'fp': cm[0,1], 'fn': cm[1,0], 'tp': cm[1,1]
                })

    return pd.DataFrame(results), feature_rankings, confusion_mats

print('Experiment function ready (Pearson Correlation)')
print(f'  HIGH input: top-{N_TOP_FEATURES} feature types × ALL channels')
print(f'  LOW  input: bottom-{N_BOTTOM_FEATURES} feature types × ALL channels')

"""## 7. Run Experiments"""

all_results   = {}
all_rankings  = {}
all_conf_mats = {}

print('='*80)
print('RUNNING EXPERIMENTS')
print('='*80)
print(f'Configurations: {list(feature_matrices.keys())}')

for config in feature_matrices.keys():
    print(f'\n{"="*60}')
    print(f'{config.upper()} — {len(channel_lists[config])} channels')
    print(f'{"="*60}')

    results, rankings, conf_mats = run_experiment(
        feature_matrices[config],
        folds_dict[config],
        feature_columns[config],
        feature_types[config],
        channel_lists[config],
        channel_config=config
    )
    all_results[config]   = results
    all_rankings[config]  = rankings
    all_conf_mats[config] = conf_mats
    print(f'\n  {config} complete — {len(results)} result rows')

print(f'\n{"="*80}')
print('ALL EXPERIMENTS COMPLETE')
print(f'{"="*80}')

"""## 8. Results Aggregation"""

def aggregate_results(results_df):
    return results_df.groupby(['channel_config', 'feature_set', 'model']).agg(
        accuracy_mean  =('accuracy',  'mean'),
        accuracy_std   =('accuracy',  'std'),
        precision_mean =('precision', 'mean'),
        precision_std  =('precision', 'std'),
        recall_mean    =('recall',    'mean'),
        recall_std     =('recall',    'std'),
        f1_mean        =('f1',        'mean'),
        f1_std         =('f1',        'std'),
        n_columns_mean =('n_columns', 'mean'),
        tn_sum         =('tn', 'sum'),
        fp_sum         =('fp', 'sum'),
        fn_sum         =('fn', 'sum'),
        tp_sum         =('tp', 'sum'),
    ).round(4)

all_summaries = {}
print('='*80)
print('RESULTS SUMMARY')
print('='*80)

for config, results_df in all_results.items():
    summary = aggregate_results(results_df)
    all_summaries[config] = summary
    print(f'\n{config.upper()}:')
    print(summary.to_string())
    results_df.to_csv(OUTPUT_DIR / f'pearson_results_{config}_detailed.csv', index=False)
    summary.to_csv(OUTPUT_DIR / f'pearson_results_{config}_summary.csv')
    print(f'  → Saved: spearman_results_{config}_detailed.csv / _summary.csv')

"""## 9. Confusion Matrix Visualization"""

def plot_confusion_matrices(conf_mats, config, results_df, output_dir):
    models       = list(results_df['model'].unique())
    feature_sets = ['HIGH', 'LOW', 'HIGH+LOW']
    n_rows, n_cols = len(feature_sets), len(models)

    fig, axes = plt.subplots(n_rows, n_cols,
                              figsize=(4.5 * n_cols, 4.0 * n_rows))
    fig.suptitle(f'Confusion Matrices — {config} Spearman (Summed 3 Folds)',
                 fontsize=14, fontweight='bold', y=1.01)

    for ri, feat_set in enumerate(feature_sets):
        for ci, model_name in enumerate(models):
            ax       = axes[ri][ci]
            cm_total = np.zeros((2, 2), dtype=int)
            for fold_num in [1, 2, 3]:
                key = (fold_num, feat_set, model_name)
                if key in conf_mats:
                    cm_total += conf_mats[key]

            ConfusionMatrixDisplay(cm_total,
                                   display_labels=['Non-Stress', 'Stress']
                                   ).plot(ax=ax, colorbar=False, cmap='Blues')

            mask     = ((results_df['feature_set'] == feat_set) &
                        (results_df['model']        == model_name))
            mean_acc = results_df[mask]['accuracy'].mean()
            mean_f1  = results_df[mask]['f1'].mean()
            ax.set_title(f'{model_name} | {feat_set}\nAcc={mean_acc:.3f}  F1={mean_f1:.3f}',
                          fontsize=10)
            if ri < n_rows - 1: ax.set_xlabel('')
            if ci > 0:           ax.set_ylabel('')

    plt.tight_layout()
    out = output_dir / f'pearson_confusion_{config}.png'
    plt.savefig(out, dpi=120, bbox_inches='tight')
    plt.show()
    print(f'Saved: {out}')


print('='*80)
print('CONFUSION MATRIX VISUALIZATION')
print('='*80)
for config in all_results.keys():
    print(f'\nPlotting {config}...')
    plot_confusion_matrices(all_conf_mats[config], config, all_results[config], OUTPUT_DIR)

"""## 10. N-Feature Type Sweep

Sweeps N = number of top/bottom feature types selected.  
Input columns = N feature types × ALL channels (fixed per config).  
Compares HIGH (top-N) vs LOW (bottom-N) across all N values and models.

"""

def run_n_sweep(data, folds, feature_cols, feat_types, channels,
                 n_values, channel_config):
    sweep_results = []
    models        = get_models()
    n_ch          = len(channels)

    for n in n_values:
        print(f'  N={n:>2} ({n}×{n_ch}={n*n_ch} cols) ...', end=' ')

        for fold_info in folds:
            train_idx = fold_info['train_idx']
            test_idx  = fold_info['test_idx']

            X_tr_full   = data.loc[train_idx, feature_cols]
            y_train     = data.loc[train_idx, 'stress_binary']   # for model training
            y_train_cont= data.loc[train_idx, 'stress_label']    # for Pearson ranking
            X_te_full   = data.loc[test_idx,  feature_cols]
            y_test      = data.loc[test_idx,  'stress_binary']

            scaler    = StandardScaler()
            X_tr_sc   = pd.DataFrame(scaler.fit_transform(X_tr_full),
                                      columns=feature_cols, index=train_idx)
            X_te_sc   = pd.DataFrame(scaler.transform(X_te_full),
                                      columns=feature_cols, index=test_idx)

            ranked, _ = rank_feature_types_by_pearson(
                X_tr_sc, y_train_cont, feat_types, channels)

            high_c, low_c, _, _ = select_feature_sets(ranked, channels, n, n)

            for feat_set_name, cols in [('HIGH', high_c), ('LOW', low_c)]:
                cols = [c for c in cols if c in X_tr_sc.columns]
                if not cols:
                    continue
                for model_name, model in models.items():
                    model.fit(X_tr_sc[cols], y_train)
                    y_pred = model.predict(X_te_sc[cols])
                    sweep_results.append({
                        'channel_config': channel_config,
                        'n_feat'        : n,
                        'n_columns'     : len(cols),
                        'feature_set'   : feat_set_name,
                        'model'         : model_name,
                        'fold'          : fold_info['fold'],
                        'accuracy'      : accuracy_score(y_test, y_pred),
                        'f1'            : f1_score(y_test, y_pred, zero_division=0)
                    })
        print('done')

    return pd.DataFrame(sweep_results)

all_sweep_results = {}
print('='*80)
print('N-FEATURE TYPE SWEEP')
print('='*80)
print(f'N values: {N_FEATURE_SWEEP}')

for config in feature_matrices.keys():
    print(f'\n{config} ({len(channel_lists[config])} channels fixed):')
    sweep_df = run_n_sweep(
        feature_matrices[config], folds_dict[config],
        feature_columns[config], feature_types[config],
        channel_lists[config], N_FEATURE_SWEEP, channel_config=config)
    all_sweep_results[config] = sweep_df
    sweep_df.to_csv(OUTPUT_DIR / f'pearson_sweep_{config}.csv', index=False)
    print(f'  Saved: pearson_sweep_{config}.csv')

def plot_n_sweep(sweep_df, config, n_ch, output_dir):
    """
    Line plot: accuracy vs N feature types for HIGH and LOW.
    One subplot per model. Shading = ±1 std across folds.
    """
    models = list(sweep_df['model'].unique())
    colors = {'HIGH': '#2563EB', 'LOW': '#DC2626'}

    fig, axes = plt.subplots(1, len(models), figsize=(5 * len(models), 4.5),
                              sharey=True)
    if len(models) == 1:
        axes = [axes]

    for ax, model_name in zip(axes, models):
        for feat_set in ['HIGH', 'LOW']:
            sub   = sweep_df[(sweep_df['model'] == model_name) &
                              (sweep_df['feature_set'] == feat_set)]
            stats = sub.groupby('n_feat')['accuracy'].agg(
                mean='mean', std='std').reset_index()

            ax.plot(stats['n_feat'], stats['mean'], marker='o', linewidth=2,
                    markersize=6, color=colors[feat_set], label=feat_set)
            ax.fill_between(stats['n_feat'],
                            stats['mean'] - stats['std'],
                            stats['mean'] + stats['std'],
                            alpha=0.15, color=colors[feat_set])

        ax.axhline(MAJORITY_BASELINE, color='gray', linestyle='--', linewidth=1.5,
                   label=f'Majority baseline ({MAJORITY_BASELINE:.3f})')
        ax.set_title(model_name, fontsize=12, fontweight='bold')
        ax.set_xlabel('N feature types selected', fontsize=10)
        ax.set_ylabel('Accuracy', fontsize=10)
        ax.set_xticks(N_FEATURE_SWEEP)
        ax.set_xticklabels([f'{n}\n({n*n_ch} cols)' for n in N_FEATURE_SWEEP], fontsize=8)
        ax.set_ylim(0.35, 0.80)
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.3)

    fig.suptitle(
        f'Accuracy vs N Feature Types — {config} ({n_ch} channels, all used)\n'
        f'HIGH = top-N × {n_ch}ch, LOW = bottom-N × {n_ch}ch  |  shading = ±1 std',
        fontsize=12, fontweight='bold')
    plt.tight_layout()
    out = output_dir / f'pearson_n_sweep_{config}.png'
    plt.savefig(out, dpi=150, bbox_inches='tight')
    plt.show()
    print(f'Saved: {out}')


def print_sweep_summary(sweep_df, config):
    print(f'\n{"="*80}')
    print(f'SWEEP SUMMARY — {config}')
    print(f'{"="*80}')
    print(f'  {"Model":<10} {"Set":<6} {"Best N":>7} {"Columns":>8} {"Accuracy":>10} {"F1":>8}')
    print(f'  {"-"*10} {"-"*6} {"-"*7} {"-"*8} {"-"*10} {"-"*8}')

    for model in sweep_df['model'].unique():
        for feat_set in ['HIGH', 'LOW']:
            sub  = sweep_df[(sweep_df['model'] == model) &
                            (sweep_df['feature_set'] == feat_set)]
            agg  = sub.groupby('n_feat')[['accuracy','f1','n_columns']].mean()
            best = agg['accuracy'].idxmax()
            print(f'  {model:<10} {feat_set:<6} {best:>7} '
                  f'{agg.loc[best,"n_columns"]:>8.0f} '
                  f'{agg.loc[best,"accuracy"]:>10.4f} '
                  f'{agg.loc[best,"f1"]:>8.4f}')

    agg_all = sweep_df.groupby(['feature_set','n_feat','model'])['accuracy'].mean()
    best    = agg_all.idxmax()
    print(f'\n  Overall best: Set={best[0]}, N={best[1]}, Model={best[2]}, '
          f'Accuracy={agg_all.max():.4f}')


print('='*80)
print('SWEEP PLOTS & SUMMARY')
print('='*80)
for config, sweep_df in all_sweep_results.items():
    plot_n_sweep(sweep_df, config, len(channel_lists[config]), OUTPUT_DIR)
    print_sweep_summary(sweep_df, config)

"""## 11. Global vs Training Correlation Comparison

Compares feature-type rankings **and classifier input pairs** from the training subset (2/3 trials, per fold)
vs correlations from the full dataset (global CSVs, all trials).

**Part A — Feature-type ranking agreement:**
- Spearman ρ between global feature ranking and per-fold training ranking
- Top-N Jaccard: fraction of top-N feature types that overlap

**Part B — Classifier input pair (feature × channel) overlap:**
- Training HIGH pairs = `{top-N feature types} × {all channels}` — the actual classifier input
- Global top-K pairs  = top-K (feature, channel) pairs from `spearman_channel_binary.csv` ranked by `abs_rho`
- **Precision**: fraction of training HIGH pairs that appear in global top-K
- **Recall**: fraction of global top-K pairs captured by training HIGH selection
- **Jaccard**: set overlap between the two pair sets
- Also compared for LOW pairs (expected: low overlap with global top pairs)
- Visualised as a heatmap: rows = feature types, cols = channels, cell colour = global `abs_rho`,
  with markers showing which cells are selected as HIGH / LOW by training

"""

GLOBAL_FEATURE_CSVS = {
    '32ch': GLOBAL_FEATURE_CSV_32CH,
    '24ch': GLOBAL_FEATURE_CSV_24CH,
}
GLOBAL_CHANNEL_CSVS = {
    '32ch': GLOBAL_CHANNEL_CSV_32CH,
    '24ch': GLOBAL_CHANNEL_CSV_24CH,
}


# ─────────────────────────────────────────────────────────────────────────────
# A. Feature-type ranking comparison (same as before)
# ─────────────────────────────────────────────────────────────────────────────

def load_global_feature_ranking(config):
    """
    Load global feature correlation CSV.
    Handles both Pearson (correlations.csv) and Spearman (spearman_feature_binary.csv) formats.

    Pearson CSV columns : feature, correlation, abs_correlation, p_value, n_samples
    Spearman CSV columns: feature, spearman_rho, abs_rho, p_value, n_samples

    Returns sorted list of (feature_type, abs_corr), descending.
    """
    df = pd.read_csv(GLOBAL_FEATURE_CSVS[config])
    df.columns = [c.strip().lower().replace('-','_').replace(' ','_') for c in df.columns]

    # Detect feature column
    feat_col = next((c for c in df.columns if c in ('feature','feature_name')), None)
    if feat_col is None:
        feat_col = next(c for c in df.columns if 'feature' in c)

    # Detect absolute correlation column — prefer explicit 'abs_correlation' (Pearson) or 'abs_rho' (Spearman)
    if 'abs_correlation' in df.columns:
        abs_col = 'abs_correlation'
    elif 'abs_rho' in df.columns:
        abs_col = 'abs_rho'
    else:
        abs_col = next(c for c in df.columns if 'abs' in c)

    df = df.sort_values(abs_col, ascending=False).reset_index(drop=True)
    return list(zip(df[feat_col], df[abs_col]))


def compare_feature_rankings(global_ranked, per_fold_ranked, top_n_list=(3, 5, 10)):
    """
    Spearman rank correlation + Jaccard top-N between global and per-fold training rankings.
    """
    global_names = [n for n, _ in global_ranked]
    global_rank  = {n: i for i, n in enumerate(global_names)}
    records = []
    rho_list = []

    print(f'  {"Fold":<6} {"Spearman ρ":>12} {"p-value":>10}', end='')
    for n in top_n_list:
        print(f'  {"Top-"+str(n)+" Jaccard":>14}', end='')
    print()
    print(f'  {"-"*6} {"-"*12} {"-"*10}', end='')
    for _ in top_n_list:
        print(f'  {"-"*14}', end='')
    print()

    for fold_i, fold_ranking in enumerate(per_fold_ranked, 1):
        train_names = [r[0] for r in fold_ranking]
        train_rank  = {n: i for i, n in enumerate(train_names)}
        common = [n for n in global_names if n in train_rank]
        if len(common) < 3:
            print(f'  Fold {fold_i}: too few common features ({len(common)}), skipping')
            continue

        rho, p = spearmanr([global_rank[n] for n in common],
                           [train_rank[n]  for n in common])
        rho_list.append(rho)

        print(f'  {fold_i:<6} {rho:>12.4f} {p:>10.4f}', end='')
        for n in top_n_list:
            g_top = set(global_names[:n])
            t_top = set(train_names[:n])
            jac   = len(g_top & t_top) / len(g_top | t_top) if (g_top | t_top) else 0.0
            print(f'  {jac:>14.2%}', end='')
        print()
        records.append({'fold': fold_i, 'rho': rho, 'p': p, 'train_names': train_names})

    if rho_list:
        mean_rho = np.mean(rho_list)
        print(f'\n  Mean Spearman ρ: {mean_rho:.4f} ± {np.std(rho_list):.4f}')
        if   mean_rho >= 0.8: interp = 'VERY HIGH — training subset reproduces global ranking reliably'
        elif mean_rho >= 0.6: interp = 'HIGH — minor variation, training subset sufficient'
        elif mean_rho >= 0.4: interp = 'MODERATE — some ranking shifts; caution advised'
        else:                  interp = 'LOW — training subset unreliable; full data preferred'
        print(f'  Interpretation : {interp}')

    return records


def plot_global_vs_training(global_ranked, per_fold_ranked, config, output_dir):
    """Scatter: global rank vs avg training rank ± std."""
    global_names = [n for n, _ in global_ranked]
    g_rank       = {n: i for i, n in enumerate(global_names)}
    all_train_ranks = {n: [] for n in global_names}
    for fold_ranking in per_fold_ranked:
        t_rank = {r[0]: i for i, r in enumerate(fold_ranking)}
        for n in global_names:
            if n in t_rank:
                all_train_ranks[n].append(t_rank[n])

    names   = [n for n in global_names if all_train_ranks[n]]
    g_ranks = [g_rank[n]                   for n in names]
    t_means = [np.mean(all_train_ranks[n]) for n in names]
    t_stds  = [np.std(all_train_ranks[n])  for n in names]
    rho_overall = spearmanr(g_ranks, t_means)[0]

    fig, ax = plt.subplots(figsize=(8, 6))
    ax.errorbar(g_ranks, t_means, yerr=t_stds, fmt='o', alpha=0.65,
                color='#2563EB', markersize=6, elinewidth=1, capsize=3,
                label='Feature types (mean ± std training rank)')
    max_r = max(max(g_ranks), max(t_means)) + 1
    ax.plot([0, max_r], [0, max_r], 'k--', alpha=0.4, linewidth=1.3,
            label='Perfect agreement (y = x)')
    for gr, tm, name in zip(g_ranks, t_means, names):
        if abs(gr - tm) > 3:
            ax.annotate(name, (gr, tm), fontsize=8, alpha=0.8,
                        xytext=(5, 3), textcoords='offset points')
    ax.set_xlabel('Global rank (full dataset)', fontsize=12)
    ax.set_ylabel('Avg training rank ± std (2/3 trials per fold)', fontsize=12)
    ax.set_title(f'Feature-type Ranking: Global vs Training — {config}\n'
                 f'Rank Spearman ρ = {rho_overall:.3f}', fontsize=13, fontweight='bold')
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    out = output_dir / f'pearson_global_vs_training_feat_{config}.png'
    plt.savefig(out, dpi=130, bbox_inches='tight')
    plt.show()
    print(f'Saved: {out}')


# ─────────────────────────────────────────────────────────────────────────────
# B. Classifier input pair (feature × channel) overlap with global top pairs
# ─────────────────────────────────────────────────────────────────────────────

def load_global_channel_pairs(config):
    """
    Load global channel correlation CSV.
    Handles both Pearson (channel_correlations.csv) and Spearman (spearman_channel_binary.csv).

    Pearson CSV columns : feature_name, channel, correlation, abs_correlation, p_value, n_samples
    Spearman CSV columns: feature_name/feature, channel, spearman_rho, abs_rho, p_value, n_samples

    Returns:
        pairs_ranked : list of (feature, channel, abs_corr) sorted desc
        pair_rho_df  : DataFrame with columns [feature, channel, abs_rho] for heatmap use
    """
    df = pd.read_csv(GLOBAL_CHANNEL_CSVS[config])
    df.columns = [c.strip().lower().replace('-','_').replace(' ','_') for c in df.columns]

    ch_col   = next(c for c in df.columns if 'channel' in c)
    feat_col = next((c for c in df.columns if c in ('feature_name','feature')), None)
    if feat_col is None:
        feat_col = next(c for c in df.columns if 'feature' in c)

    # Prefer explicit abs_correlation (Pearson) then abs_rho (Spearman)
    if 'abs_correlation' in df.columns:
        abs_col = 'abs_correlation'
    elif 'abs_rho' in df.columns:
        abs_col = 'abs_rho'
    else:
        abs_col = next(c for c in df.columns if 'abs' in c)

    df = df.sort_values(abs_col, ascending=False).reset_index(drop=True)
    pairs_ranked = list(zip(df[feat_col], df[ch_col], df[abs_col]))

    pair_rho_df = df[[feat_col, ch_col, abs_col]].copy()
    pair_rho_df.columns = ['feature', 'channel', 'abs_rho']
    return pairs_ranked, pair_rho_df


def compare_pair_overlap(pairs_ranked_global, fold_rankings, channels,
                         top_k_global_list=(40, 80, 160)):
    """
    Compare training HIGH/LOW classifier input pairs vs global top-K pairs.

    Training HIGH pairs = {(ft, ch) : ft in high_feats, ch in all channels}
    Training LOW  pairs = {(ft, ch) : ft in low_feats,  ch in all channels}
    Global top-K  pairs = top-K (feature, channel) by global abs_rho

    Metrics per fold:
      - Precision : |train_set ∩ global_top_K| / |train_set|
                    (fraction of training pairs that are globally high)
      - Recall    : |train_set ∩ global_top_K| / |global_top_K|
                    (fraction of global top-K captured by training selection)
      - Jaccard   : |train_set ∩ global_top_K| / |train_set ∪ global_top_K|
    """
    global_pair_set_full = [(ft, ch) for ft, ch, _ in pairs_ranked_global]

    records = []

    for feat_set_label in ['HIGH', 'LOW']:
        print(f'\n  {feat_set_label} pairs vs Global top-K:')
        print(f'  {"Fold":<6}', end='')
        for k in top_k_global_list:
            print(f'  {"Top-"+str(k):>8} Prec  Rec   Jac', end='')
        print()
        print(f'  {"-"*6}', end='')
        for _ in top_k_global_list:
            print(f'  {"-"*8} {"─"*5} {"─"*5} {"─"*5}', end='')
        print()

        for fold in fold_rankings:
            fold_num   = fold['fold']
            feat_list  = fold['high_feats'] if feat_set_label == 'HIGH' else fold['low_feats']
            train_pairs = set((ft, ch) for ft in feat_list for ch in channels)

            print(f'  {fold_num:<6}', end='')
            fold_record = {'fold': fold_num, 'set': feat_set_label,
                           'n_train_pairs': len(train_pairs)}
            for k in top_k_global_list:
                global_top_k = set(global_pair_set_full[:k])
                intersect    = train_pairs & global_top_k
                union_       = train_pairs | global_top_k
                precision    = len(intersect) / len(train_pairs)   if train_pairs   else 0.0
                recall       = len(intersect) / len(global_top_k)  if global_top_k  else 0.0
                jaccard      = len(intersect) / len(union_)         if union_        else 0.0
                print(f'  K={k:<5} {precision:>5.2%} {recall:>5.2%} {jaccard:>5.2%}', end='')
                fold_record[f'k{k}_precision'] = precision
                fold_record[f'k{k}_recall']    = recall
                fold_record[f'k{k}_jaccard']   = jaccard
            print()
            records.append(fold_record)

        # Mean across folds for this feat_set
        set_records = [r for r in records if r['set'] == feat_set_label]
        print(f'  Mean  ', end='')
        for k in top_k_global_list:
            p_mean = np.mean([r[f'k{k}_precision'] for r in set_records])
            r_mean = np.mean([r[f'k{k}_recall']    for r in set_records])
            j_mean = np.mean([r[f'k{k}_jaccard']   for r in set_records])
            print(f'  K={k:<5} {p_mean:>5.2%} {r_mean:>5.2%} {j_mean:>5.2%}', end='')
        print()

    return pd.DataFrame(records)


def plot_pair_overlap_heatmap(pair_rho_df, fold_rankings, channels, config, output_dir):
    """
    Heatmap: rows = feature types, cols = channels, cell = global abs_rho.
    Overlaid markers show which cells are selected as HIGH (★) or LOW (✕) by training.
    One subplot per fold.
    """
    feat_types_ordered = (pair_rho_df.groupby('feature')['abs_rho']
                          .mean().sort_values(ascending=False).index.tolist())
    channels_ordered   = (pair_rho_df.groupby('channel')['abs_rho']
                          .mean().sort_values(ascending=False).index.tolist())
    # Keep only channels present in this config
    channels_ordered   = [ch for ch in channels_ordered if ch in channels]

    # Pivot: rows=feature, cols=channel
    pivot = pair_rho_df.pivot_table(index='feature', columns='channel',
                                     values='abs_rho', aggfunc='mean')
    pivot = pivot.reindex(index=feat_types_ordered,
                          columns=channels_ordered).fillna(0)

    n_folds = len(fold_rankings)
    fig, axes = plt.subplots(1, n_folds,
                              figsize=(max(12, len(channels_ordered) * 0.55) * n_folds / 2,
                                       max(6,  len(feat_types_ordered) * 0.45)))
    if n_folds == 1:
        axes = [axes]

    for ax, fold in zip(axes, fold_rankings):
        fold_num   = fold['fold']
        high_feats = set(fold['high_feats'])
        low_feats  = set(fold['low_feats'])

        im = ax.imshow(pivot.values, aspect='auto', cmap='YlOrRd',
                       vmin=0, vmax=pivot.values.max())
        plt.colorbar(im, ax=ax, fraction=0.03, pad=0.03, label='Global |Pearson r| (32ch) / |Spearman ρ| (24ch)')

        ax.set_xticks(range(len(channels_ordered)))
        ax.set_xticklabels(channels_ordered, rotation=90, fontsize=7)
        ax.set_yticks(range(len(feat_types_ordered)))
        ax.set_yticklabels(feat_types_ordered, fontsize=7)
        ax.set_title(f'Fold {fold_num} — Global abs_rho heatmap\n'
                     f'★ = HIGH selected  ✕ = LOW selected', fontsize=10, fontweight='bold')

        # Overlay markers
        for fi, feat in enumerate(feat_types_ordered):
            for ci, ch in enumerate(channels_ordered):
                if feat in high_feats:
                    ax.text(ci, fi, '★', ha='center', va='center',
                            fontsize=7, color='#1d4ed8', fontweight='bold')
                elif feat in low_feats:
                    ax.text(ci, fi, '✕', ha='center', va='center',
                            fontsize=7, color='#6b7280')

    fig.suptitle(f'Feature × Channel Global Correlation Heatmap — {config}\n'
                 f'(★ = training HIGH input, ✕ = training LOW input)\n'
                 f'Color = Global |r| (32ch) / |ρ| (24ch)',
                 fontsize=12, fontweight='bold')
    plt.tight_layout()
    out = output_dir / f'pearson_pair_heatmap_{config}.png'
    plt.savefig(out, dpi=130, bbox_inches='tight')
    plt.show()
    print(f'Saved: {out}')


# ─────────────────────────────────────────────────────────────────────────────
# Run Part A + B for all configs
# ─────────────────────────────────────────────────────────────────────────────
print('='*80)
print('GLOBAL (Pearson) vs TRAINING CORRELATION COMPARISON')
print('='*80)

all_pair_records = {}

for config, rankings in all_rankings.items():
    print(f'\n{"─"*70}')
    print(f'{config.upper()}  ({len(channel_lists[config])} channels)')
    print(f'{"─"*70}')

    # ── Part A: Feature-type ranking ─────────────────────────────────────
    print('\n[A] Feature-type ranking: Global (Pearson/32ch, Spearman/24ch) vs Training (Pearson)')
    print(f'    Global  = all trials (full dataset)  |  Training = 2/3 trials per fold')
    try:
        global_feat_ranked = load_global_feature_ranking(config)
        print(f'    Global feature types: {len(global_feat_ranked)}')
    except FileNotFoundError as e:
        print(f'    WARNING: {e} — skipping Part A')
        global_feat_ranked = None

    if global_feat_ranked:
        per_fold_ranked = [fold['ranked'] for fold in rankings]
        compare_feature_rankings(global_feat_ranked, per_fold_ranked, top_n_list=(3, 5, 10))
        plot_global_vs_training(global_feat_ranked, per_fold_ranked, config, OUTPUT_DIR)

    # ── Part B: Classifier input pair (feature × channel) overlap ────────
    print('\n[B] Classifier input pairs (feature × channel): Training vs Global top-K')
    print(f'    Training HIGH pairs = top-{N_TOP_FEATURES} feat types × all {len(channel_lists[config])} channels'
          f' = {N_TOP_FEATURES * len(channel_lists[config])} pairs per fold')
    print(f'    Training LOW  pairs = bottom-{N_BOTTOM_FEATURES} feat types × all channels'
          f' = {N_BOTTOM_FEATURES * len(channel_lists[config])} pairs per fold')
    try:
        pairs_ranked_global, pair_rho_df = load_global_channel_pairs(config)
        print(f'    Global pairs loaded : {len(pairs_ranked_global)} (channel × feature combos)')
    except FileNotFoundError as e:
        print(f'    WARNING: {e} — skipping Part B')
        pairs_ranked_global = None

    if pairs_ranked_global:
        n_ch      = len(channel_lists[config])
        # K values: cover ~1x, ~2x, ~4x the size of one HIGH set
        k_values  = sorted(set([
            N_TOP_FEATURES * n_ch,
            N_TOP_FEATURES * n_ch * 2,
            N_TOP_FEATURES * n_ch * 4,
        ]))
        print(f'    K values tested     : {k_values}')

        pair_df = compare_pair_overlap(
            pairs_ranked_global, rankings, channel_lists[config],
            top_k_global_list=k_values)

        all_pair_records[config] = pair_df
        pair_df.to_csv(OUTPUT_DIR / f'pearson_pair_overlap_{config}.csv', index=False)
        print(f'    Saved: pearson_pair_overlap_{config}.csv')

        print(f'\n    Interpretation:')
        for feat_set_label in ['HIGH', 'LOW']:
            k = k_values[0]   # use smallest K (most stringent)
            sub_recs = pair_df[pair_df['set'] == feat_set_label]
            mean_p   = sub_recs[f'k{k}_precision'].mean()
            mean_r   = sub_recs[f'k{k}_recall'].mean()
            print(f'    {feat_set_label} (K={k}): avg Precision={mean_p:.2%}, avg Recall={mean_r:.2%}')
            if feat_set_label == 'HIGH':
                if mean_p >= 0.5:
                    note = 'majority of training HIGH pairs are globally high-correlation ✓'
                elif mean_p >= 0.25:
                    note = 'moderate overlap — training captures some globally high pairs'
                else:
                    note = 'low overlap — training HIGH selection differs from global ranking'
                print(f'    → {note}')

        plot_pair_overlap_heatmap(pair_rho_df, rankings, channel_lists[config],
                                   config, OUTPUT_DIR)

# ─────────────────────────────────────────────────────────────────────────────
# C. Channel ranking comparison: Global vs Training
# Tambahkan di bagian bawah cell 27, setelah Part B selesai dijalankan
# ─────────────────────────────────────────────────────────────────────────────

def get_global_channel_ranking(pair_rho_df):
    """
    Agregasi avg abs_corr per channel dari global pair_rho_df.
    pair_rho_df kolom: [feature, channel, abs_rho]
    Returns: list of (channel, avg_abs_corr) sorted descending.
    """
    ch_agg = (pair_rho_df
              .groupby('channel')['abs_rho']
              .mean()
              .sort_values(ascending=False)
              .reset_index())
    ch_agg.columns = ['channel', 'avg_abs_corr']
    return list(zip(ch_agg['channel'], ch_agg['avg_abs_corr']))


def get_training_channel_ranking(col_rho, channels):
    """
    Agregasi avg |corr| per channel dari col_rho hasil per-fold ranking.
    col_rho: dict { 'feat_type_CHANNEL': (rho, abs_rho, p) }
    Returns: list of (channel, avg_abs_corr) sorted descending.
    """
    ch_abs = {ch: [] for ch in channels}
    for col_name, (rho, abs_rho, p) in col_rho.items():
        # col_name format: {feat_type}_{channel}
        for ch in channels:
            if col_name.endswith(f'_{ch}'):
                ch_abs[ch].append(abs_rho)
                break

    ch_avg = [(ch, float(np.mean(vals))) for ch, vals in ch_abs.items() if vals]
    ch_avg.sort(key=lambda x: x[1], reverse=True)
    return ch_avg


def compare_channel_rankings(global_ch_ranked, fold_rankings, channels,
                              top_m_list=(5, 10, 16)):
    """
    Bandingkan global channel ranking vs per-fold training channel ranking.

    Metrics per fold:
      - Spearman ρ: konsistensi urutan channel
      - Jaccard top-M: overlap channel terbaik
    """
    global_names = [ch for ch, _ in global_ch_ranked]
    global_rank  = {ch: i for i, ch in enumerate(global_names)}

    rho_list = []
    records  = []

    print(f'  {"Fold":<6} {"Spearman ρ":>12} {"p-value":>10}', end='')
    for m in top_m_list:
        print(f'  {"Top-"+str(m)+" Jaccard":>14}', end='')
    print()
    print(f'  {"-"*6} {"-"*12} {"-"*10}', end='')
    for _ in top_m_list:
        print(f'  {"-"*14}', end='')
    print()

    for fold in fold_rankings:
        fold_num   = fold['fold']
        col_rho    = fold['col_rho']

        train_ch_ranked = get_training_channel_ranking(col_rho, channels)
        train_names     = [ch for ch, _ in train_ch_ranked]
        train_rank      = {ch: i for i, ch in enumerate(train_names)}

        common = [ch for ch in global_names if ch in train_rank]
        if len(common) < 3:
            print(f'  Fold {fold_num}: too few common channels ({len(common)}), skipping')
            continue

        rho, p = spearmanr([global_rank[ch] for ch in common],
                           [train_rank[ch]  for ch in common])
        rho_list.append(rho)

        print(f'  {fold_num:<6} {rho:>12.4f} {p:>10.4f}', end='')

        fold_rec = {'fold': fold_num, 'rho': rho, 'p': p,
                    'train_ch_ranked': train_ch_ranked}
        for m in top_m_list:
            g_top = set(global_names[:m])
            t_top = set(train_names[:m])
            jac   = len(g_top & t_top) / len(g_top | t_top) if (g_top | t_top) else 0.0
            print(f'  {jac:>14.2%}', end='')
            fold_rec[f'm{m}_jaccard'] = jac
        print()
        records.append(fold_rec)

    if rho_list:
        mean_rho = np.mean(rho_list)
        std_rho  = np.std(rho_list)
        print(f'\n  Mean Spearman ρ : {mean_rho:.4f} ± {std_rho:.4f}')

        if   mean_rho >= 0.8: interp = 'VERY HIGH — training subset reproduces global channel ranking reliably'
        elif mean_rho >= 0.6: interp = 'HIGH — minor variation, channel ranking mostly consistent'
        elif mean_rho >= 0.4: interp = 'MODERATE — some channel rank shifts across folds'
        else:                  interp = 'LOW — channel ranking unstable; training subset insufficient'
        print(f'  Interpretation  : {interp}')

        # Top-M mean Jaccard summary
        print(f'\n  Mean Jaccard across folds:')
        for m in top_m_list:
            mean_jac = np.mean([r[f'm{m}_jaccard'] for r in records])
            print(f'    Top-{m:<3}: {mean_jac:.2%}')

    return records


def plot_channel_ranking_scatter(global_ch_ranked, fold_rankings, channels,
                                  config, output_dir):
    """
    Scatter: global channel rank (x) vs avg training channel rank ± std (y).
    """
    global_names = [ch for ch, _ in global_ch_ranked]
    g_rank       = {ch: i for i, ch in enumerate(global_names)}

    all_train_ranks = {ch: [] for ch in global_names}
    for fold in fold_rankings:
        train_ch = get_training_channel_ranking(fold['col_rho'], channels)
        t_rank   = {ch: i for i, ch in enumerate([c for c, _ in train_ch])}
        for ch in global_names:
            if ch in t_rank:
                all_train_ranks[ch].append(t_rank[ch])

    names   = [ch for ch in global_names if all_train_ranks[ch]]
    g_ranks = [g_rank[ch]                    for ch in names]
    t_means = [np.mean(all_train_ranks[ch])  for ch in names]
    t_stds  = [np.std(all_train_ranks[ch])   for ch in names]
    rho_overall = spearmanr(g_ranks, t_means)[0]

    fig, ax = plt.subplots(figsize=(8, 6))
    ax.errorbar(g_ranks, t_means, yerr=t_stds, fmt='o', alpha=0.7,
                color='#16a34a', markersize=7, elinewidth=1.2, capsize=3,
                label='Channels (mean ± std training rank)')

    # Annotate all channel names
    for gr, tm, name in zip(g_ranks, t_means, names):
        ax.annotate(name, (gr, tm), fontsize=7.5, alpha=0.85,
                    xytext=(4, 3), textcoords='offset points')

    max_r = max(max(g_ranks), max(t_means)) + 1
    ax.plot([0, max_r], [0, max_r], 'k--', alpha=0.4, linewidth=1.3,
            label='Perfect agreement (y = x)')

    ax.set_xlabel('Global channel rank (full dataset)', fontsize=12)
    ax.set_ylabel('Avg training channel rank ± std (2/3 trials)', fontsize=12)
    ax.set_title(f'Channel Ranking: Global vs Training — {config}\n'
                 f'Rank Spearman ρ = {rho_overall:.3f}', fontsize=13, fontweight='bold')
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    out = output_dir / f'pearson_global_vs_training_channel_{config}.png'  # ganti 'pearson' → 'spearman' untuk notebook Spearman
    plt.savefig(out, dpi=130, bbox_inches='tight')
    plt.show()
    print(f'Saved: {out}')


# ── Run Part C for all configs ────────────────────────────────────────────────
for config, rankings in all_rankings.items():
    print(f'\n{"─"*70}')
    print(f'[C] Channel ranking: Global vs Training — {config}')
    print(f'    Global  = full dataset  |  Training = 2/3 trials per fold')
    print(f'    Aggregation = mean avg|corr| per channel across all feature types')
    print(f'{"─"*70}')

    if config not in [k for k in all_pair_records]:
        print(f'  WARNING: pair_rho_df not available for {config} — run Part B first')
        continue

    # Rebuild pair_rho_df from global channel CSV
    try:
        _, pair_rho_df_c = load_global_channel_pairs(config)
    except FileNotFoundError as e:
        print(f'  WARNING: {e} — skipping Part C')
        continue

    global_ch_ranked = get_global_channel_ranking(pair_rho_df_c)
    n_ch = len(channel_lists[config])
    top_m_values = sorted(set([5, 10, min(16, n_ch), n_ch // 2]))

    print(f'\n  Global top channels (avg |corr| across all features):')
    print(f'  {"Rank":<5} {"Channel":<10} {"avg|corr|":>10}')
    print(f'  {"-"*5} {"-"*10} {"-"*10}')
    for i, (ch, avg) in enumerate(global_ch_ranked[:10], 1):
        print(f'  {i:<5} {ch:<10} {avg:>10.6f}')

    print(f'\n  Spearman ρ & Jaccard — Global vs Training channel ranking:')
    ch_rank_records = compare_channel_rankings(
        global_ch_ranked, rankings, channel_lists[config],
        top_m_list=top_m_values
    )

    plot_channel_ranking_scatter(
        global_ch_ranked, rankings, channel_lists[config],
        config, OUTPUT_DIR
    )

    # Save
    ch_rank_df = pd.DataFrame([
        {'fold': r['fold'], 'rho': r['rho'], 'p': r['p'],
         **{k: v for k, v in r.items() if k.startswith('m')}}
        for r in ch_rank_records
    ])
    out_csv = OUTPUT_DIR / f'pearson_channel_rank_comparison_{config}.csv'  # ganti 'pearson' → 'spearman' untuk notebook Spearman
    ch_rank_df.to_csv(out_csv, index=False)
    print(f'\n  Saved: {out_csv.name}')

"""## 12. Key Analyses: HIGH vs LOW Performance"""

def analyze_high_vs_low(results_df, channel_config):
    subset = results_df[results_df['channel_config'] == channel_config]
    n_ch   = subset['n_channels'].iloc[0]

    print(f'\n{"="*80}')
    print(f'ANALYSIS: {channel_config}  ({n_ch} channels, all used)')
    print(f'{"="*80}')

    print('\n1. HIGH vs LOW — Accuracy & F1:')
    print(f'  {"─"*70}')
    print(f'  {"Model":<10} {"HIGH acc":>10} {"LOW acc":>10} {"Diff":>8}'
          f' {"HIGH F1":>9} {"LOW F1":>8}')
    print(f'  {"-"*10} {"-"*10} {"-"*10} {"-"*8} {"-"*9} {"-"*8}')
    for model in subset['model'].unique():
        md_      = subset[subset['model'] == model]
        h_acc    = md_[md_['feature_set'] == 'HIGH']['accuracy'].mean()
        l_acc    = md_[md_['feature_set'] == 'LOW']['accuracy'].mean()
        h_f1     = md_[md_['feature_set'] == 'HIGH']['f1'].mean()
        l_f1     = md_[md_['feature_set'] == 'LOW']['f1'].mean()
        diff     = h_acc - l_acc
        arrow    = '▲' if diff > 0 else ('▼' if diff < 0 else '=')
        print(f'  {model:<10} {h_acc:>10.4f} {l_acc:>10.4f} {diff:>+8.4f}'
              f' {arrow}  {h_f1:>7.4f}  {l_f1:>6.4f}')

    print('\n2. Stability (Accuracy Std across folds):')
    print(f'  {"─"*50}')
    for model in subset['model'].unique():
        md_      = subset[subset['model'] == model]
        h_std    = md_[md_['feature_set'] == 'HIGH']['accuracy'].std()
        l_std    = md_[md_['feature_set'] == 'LOW']['accuracy'].std()
        stabler  = 'HIGH' if h_std <= l_std else 'LOW'
        print(f'  {model:<10}  HIGH_std={h_std:.4f}  LOW_std={l_std:.4f}'
              f'  → more stable: {stabler}')

    print(f'\n3. vs Majority Baseline ({MAJORITY_BASELINE:.4f}):')
    print(f'  {"─"*60}')
    for feat_set in ['HIGH', 'LOW']:
        for model in subset['model'].unique():
            acc  = subset[(subset['feature_set']==feat_set) &
                          (subset['model']==model)]['accuracy'].mean()
            diff = acc - MAJORITY_BASELINE
            mark = '✓ ABOVE' if diff > 0 else '✗ BELOW'
            print(f'  {feat_set} {model:<10}  acc={acc:.4f}  ({diff:+.4f} {mark})')

    print('\n4. HIGH+LOW vs HIGH:')
    print(f'  {"─"*60}')
    for model in subset['model'].unique():
        md_   = subset[subset['model'] == model]
        h_acc = md_[md_['feature_set'] == 'HIGH']['accuracy'].mean()
        c_acc = md_[md_['feature_set'] == 'HIGH+LOW']['accuracy'].mean()
        diff  = c_acc - h_acc
        note  = 'Complementary ↑' if diff > 0.01 else ('Neutral' if diff > -0.01 else 'Redundant/Noise ↓')
        print(f'  {model:<10}  HIGH={h_acc:.4f}  HIGH+LOW={c_acc:.4f}'
              f'  diff={diff:+.4f}  → {note}')

    print('\n5. Best configuration:')
    print(f'  {"─"*60}')
    grp  = subset.groupby(['feature_set','model'])['accuracy'].mean()
    best = grp.idxmax()
    print(f'  Feature set={best[0]}, Model={best[1]}, '
          f'Accuracy={grp.max():.4f}, '
          f'F1={subset[(subset["feature_set"]==best[0])&(subset["model"]==best[1])]["f1"].mean():.4f}')


for config, results_df in all_results.items():
    analyze_high_vs_low(results_df, config)

"""## 13. 32ch vs 24ch Channel Comparison

Compares classification performance between 32-channel and 24-channel configurations  
for HIGH and LOW feature sets. Shows whether the excluded 8 channels carry  
discriminative information.

"""

def compare_channel_configs(all_results):
    configs = list(all_results.keys())
    if len(configs) < 2:
        print('Only one configuration available — enable both RUN_32CH and RUN_24CH'
              ' to see channel comparison.')
        return

    # Combine all results
    combined = pd.concat(all_results.values(), ignore_index=True)

    print('='*80)
    print('32ch vs 24ch CHANNEL COMPARISON')
    print('='*80)

    for feat_set in ['HIGH', 'LOW']:
        print(f'\n  Feature set: {feat_set}')
        print(f'  {"Model":<10}', end='')
        for cfg in configs:
            print(f'  {cfg+" acc":>12}', end='')
        print(f'  {"Diff (32-24)":>14}')
        print(f'  {"-"*10}' + f'  {"-"*12}' * len(configs) + f'  {"-"*14}')

        for model in combined['model'].unique():
            print(f'  {model:<10}', end='')
            accs = []
            for cfg in configs:
                sub  = combined[(combined['channel_config'] == cfg) &
                                (combined['feature_set']    == feat_set) &
                                (combined['model']          == model)]
                acc  = sub['accuracy'].mean()
                accs.append(acc)
                print(f'  {acc:>12.4f}', end='')
            if len(accs) == 2:
                print(f'  {accs[0]-accs[1]:>+14.4f}')
            else:
                print()

    # Visualise
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    models     = list(combined['model'].unique())
    x          = np.arange(len(models))
    width      = 0.35
    config_colors = {'32ch': '#2563EB', '24ch': '#F59E0B'}

    for ax, feat_set in zip(axes, ['HIGH', 'LOW']):
        for i, cfg in enumerate(configs):
            accs = [combined[(combined['channel_config']==cfg) &
                             (combined['feature_set']==feat_set) &
                             (combined['model']==m)]['accuracy'].mean()
                    for m in models]
            stds = [combined[(combined['channel_config']==cfg) &
                             (combined['feature_set']==feat_set) &
                             (combined['model']==m)]['accuracy'].std()
                    for m in models]
            offset = (i - 0.5) * width
            ax.bar(x + offset, accs, width, yerr=stds, label=cfg,
                   color=config_colors.get(cfg, f'C{i}'),
                   capsize=4, alpha=0.85, edgecolor='white')

        ax.axhline(MAJORITY_BASELINE, color='gray', linestyle='--', linewidth=1.3,
                   label=f'Baseline ({MAJORITY_BASELINE:.3f})')
        ax.set_xticks(x)
        ax.set_xticklabels(models, fontsize=11)
        ax.set_ylabel('Accuracy', fontsize=11)
        ax.set_ylim(0.35, 0.82)
        ax.set_title(f'{feat_set} Feature Set', fontsize=12, fontweight='bold')
        ax.legend(fontsize=10)
        ax.grid(axis='y', alpha=0.3)

    fig.suptitle('32ch vs 24ch — HIGH and LOW Feature Sets (Pearson Selection)',
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    out = OUTPUT_DIR / 'spearman_channel_config_comparison.png'
    plt.savefig(out, dpi=130, bbox_inches='tight')
    plt.show()
    print(f'Saved: {out}')


compare_channel_configs(all_results)

"""## 14. Statistical Significance Tests: HIGH vs LOW"""

def run_statistical_tests(results_df, channel_config):
    subset = results_df[results_df['channel_config'] == channel_config]
    models = list(subset['model'].unique())

    print(f'\n{"="*80}')
    print(f'STATISTICAL TESTS — {channel_config}')
    print(f'{"="*80}')
    print('Paired observations: fold-level accuracy (n=3 folds per model)')
    print('H0: No accuracy difference between HIGH and LOW feature sets')
    print()
    print(f'  {"Model":<10} {"HIGH":>8} {"LOW":>8} {"Diff":>8}'
          f' {"Wilcoxon p":>12} {"t-test p":>10} {"Sig":>6}')
    print(f'  {"-"*10} {"-"*8} {"-"*8} {"-"*8} {"-"*12} {"-"*10} {"-"*6}')

    records = []
    for model in models:
        md_      = subset[subset['model'] == model].sort_values('fold')
        h_acc    = md_[md_['feature_set'] == 'HIGH']['accuracy'].values
        l_acc    = md_[md_['feature_set'] == 'LOW']['accuracy'].values
        diff     = h_acc.mean() - l_acc.mean()

        try:
            w_p = 1.0 if np.all(h_acc == l_acc) else wilcoxon(h_acc, l_acc)[1]
        except Exception:
            w_p = float('nan')
        try:
            t_p = ttest_rel(h_acc, l_acc)[1]
        except Exception:
            t_p = float('nan')

        sig = 'YES *' if (not np.isnan(w_p) and w_p < 0.05) else 'no'
        print(f'  {model:<10} {h_acc.mean():>8.4f} {l_acc.mean():>8.4f} {diff:>+8.4f}'
              f' {w_p:>12.4f} {t_p:>10.4f} {sig:>6}')
        records.append({'model': model, 'high_acc': h_acc.mean(), 'low_acc': l_acc.mean(),
                        'diff': diff, 'wilcoxon_p': w_p, 'ttest_p': t_p,
                        'significant': bool(not np.isnan(w_p) and w_p < 0.05)})

    n_sig = sum(r['significant'] for r in records)
    print(f'\n  Significant (p<0.05): {n_sig}/{len(models)} models')
    if n_sig == 0:
        print('  → H0 not rejected for any model.')
        print('    Note: with only 3 folds, statistical power is inherently limited.')
    else:
        print(f'  → H0 rejected for: {[r["model"] for r in records if r["significant"]]}')

    return pd.DataFrame(records)

all_stat_results = {}
print('='*80)
print('STATISTICAL SIGNIFICANCE TESTS')
print('='*80)

for config, results_df in all_results.items():
    stat_df = run_statistical_tests(results_df, config)
    all_stat_results[config] = stat_df
    stat_df.to_csv(OUTPUT_DIR / f'pearson_stat_tests_{config}.csv', index=False)
    print(f'  Saved: pearson_stat_tests_{config}.csv')

"""## 15. Feature Ranking Details Per Fold"""

def print_fold_ranking_details(rankings, config_name, n_top=5, n_bottom=5):
    print(f'\n{"="*80}')
    print(f'FEATURE RANKING DETAILS — {config_name}')
    print(f'{"="*80}')

    for r in rankings:
        fold_num = r['fold']
        ranked   = r['ranked']

        print(f'\n{"-"*70}')
        print(f'  FOLD {fold_num}  (training on trials {[t for t in [1,2,3] if t!=fold_num]})')
        print(f'{"-"*70}')
        print(f'  Total feature types: {len(ranked)}')

        print(f'\n  TOP {n_top} (HIGH) — highest avg |Spearman ρ| across all channels:')
        print(f'  {"Rank":<5} {"Feature Type":<38} {"avg|r|":>10}')
        print(f'  {"-"*5} {"-"*38} {"-"*10}')
        for i, (ft, avg, _) in enumerate(ranked[:n_top], 1):
            print(f'  {i:<5} {ft:<38} {avg:>10.6f}')

        print(f'\n  BOTTOM {n_bottom} (LOW) — lowest avg |Spearman ρ|:')
        print(f'  {"Rank":<5} {"Feature Type":<38} {"avg|r|":>10}')
        print(f'  {"-"*5} {"-"*38} {"-"*10}')
        total = len(ranked)
        for i, (ft, avg, _) in enumerate(ranked[-n_bottom:], total - n_bottom + 1):
            print(f'  {i:<5} {ft:<38} {avg:>10.6f}')

        print(f'\n  Classifier input:')
        print(f'    HIGH = {r["high_feats"]}')
        print(f'           × all {len(channel_lists[config_name])} channels = {len(r["high_cols"])} columns')


for config, rankings in all_rankings.items():
    print_fold_ranking_details(rankings, config, N_TOP_FEATURES, N_BOTTOM_FEATURES)

"""## 16. Feature Ranking Stability Across Folds"""

def analyze_ranking_stability(rankings, config_name):
    print(f'\n{"="*80}')
    print(f'FEATURE RANKING STABILITY — {config_name}')
    print(f'{"="*80}')

    def jaccard(a, b):
        a, b = set(a), set(b)
        return len(a & b) / len(a | b) if (a | b) else 1.0

    high_sets = [set(r['high_feats']) for r in rankings]
    low_sets  = [set(r['low_feats'])  for r in rankings]

    fold_pairs = [(0,1,'Fold 1 vs 2'), (0,2,'Fold 1 vs 3'), (1,2,'Fold 2 vs 3')]

    print('\n  Jaccard similarity (fold pairs):')
    print(f'  {"Pair":<15} {"HIGH Jaccard":>14} {"LOW Jaccard":>13}')
    print(f'  {"-"*15} {"-"*14} {"-"*13}')
    for i, j, lbl in fold_pairs:
        print(f'  {lbl:<15} {jaccard(high_sets[i], high_sets[j]):>14.2%}'
              f' {jaccard(low_sets[i], low_sets[j]):>13.2%}')

    h_all        = set.union(*high_sets)
    l_all        = set.union(*low_sets)
    h_consistent = set.intersection(*high_sets)
    l_consistent = set.intersection(*low_sets)

    print(f'\n  Consistency across ALL folds:')
    print(f'    HIGH: {len(h_consistent)}/{N_TOP_FEATURES} consistent'
          f' ({len(h_consistent)/N_TOP_FEATURES:.0%})  |  total unique: {len(h_all)}')
    print(f'    LOW : {len(l_consistent)}/{N_BOTTOM_FEATURES} consistent'
          f' ({len(l_consistent)/N_BOTTOM_FEATURES:.0%})  |  total unique: {len(l_all)}')

    if h_consistent:
        print(f'\n    Consistently HIGH features : {sorted(h_consistent)}')
    else:
        print('\n    No feature type is consistently HIGH across all folds')

    if l_consistent:
        print(f'    Consistently LOW features  : {sorted(l_consistent)}')
    else:
        print('    No feature type is consistently LOW across all folds')

    h_stab = len(h_consistent) / N_TOP_FEATURES
    if   h_stab >= 0.6: verdict = 'GOOD stability — feature selection is consistent'
    elif h_stab >= 0.2: verdict = 'MODERATE stability — some variation across folds'
    else:               verdict = 'LOW stability — rankings change significantly across folds'
    print(f'\n  Verdict: {verdict}')


for config, rankings in all_rankings.items():
    analyze_ranking_stability(rankings, config)

"""## 17. Final Conclusion"""

def generate_conclusion(results_df, channel_config):
    subset     = results_df[results_df['channel_config'] == channel_config]
    n_ch       = subset['n_channels'].iloc[0]
    h_mean     = subset[subset['feature_set'] == 'HIGH']['accuracy'].mean()
    l_mean     = subset[subset['feature_set'] == 'LOW']['accuracy'].mean()
    hl_mean    = subset[subset['feature_set'] == 'HIGH+LOW']['accuracy'].mean()
    h_f1       = subset[subset['feature_set'] == 'HIGH']['f1'].mean()
    l_f1       = subset[subset['feature_set'] == 'LOW']['f1'].mean()
    improve_pct = (h_mean - l_mean) / max(l_mean, 1e-9) * 100

    print(f'\n{"="*80}')
    print(f'CONCLUSION: {channel_config}  ({n_ch} channels, all used)')
    print(f'{"="*80}')
    print('\nResearch question:')
    print('  Do feature types with high Pearson r vs stress label outperform')
    print('  low-r feature types in binary stress classification,')
    print(f'  when all {n_ch} channels are used as input?')

    print(f'\nResults (avg across all models and folds):')
    print(f'  HIGH features (top-{N_TOP_FEATURES} types × {n_ch}ch): acc={h_mean:.4f}  F1={h_f1:.4f}')
    print(f'  LOW  features (bot-{N_BOTTOM_FEATURES} types × {n_ch}ch): acc={l_mean:.4f}  F1={l_f1:.4f}')
    print(f'  HIGH+LOW combined              : acc={hl_mean:.4f}')
    print(f'  Improvement (HIGH vs LOW)      : {improve_pct:+.2f}%')

    if   improve_pct > 10: answer = 'YES — STRONG EVIDENCE'
    elif improve_pct > 5:  answer = 'YES — MODERATE EVIDENCE'
    elif improve_pct > 0:  answer = 'WEAK EVIDENCE'
    else:                   answer = 'NO — NOT CONFIRMED'
    print(f'\nAnswer: {answer}')

    print(f'\nMajority baseline: {MAJORITY_BASELINE:.4f}')
    print(f'  HIGH vs baseline: {h_mean - MAJORITY_BASELINE:+.4f}'
          f'  ({"ABOVE ✓" if h_mean > MAJORITY_BASELINE else "BELOW ✗"})')

    if hl_mean > h_mean + 0.01:
        print('\nHIGH+LOW > HIGH → HIGH and LOW feature types are somewhat complementary.')
    else:
        print('\nHIGH+LOW ≈ HIGH → LOW feature types add noise; HIGH alone is sufficient.')


for config in all_results.keys():
    generate_conclusion(all_results[config], config)

"""## 18. Save Final Report"""

import sys
from io import StringIO

report     = StringIO()
old_stdout = sys.stdout
sys.stdout = report

for config in all_results.keys():
    analyze_high_vs_low(all_results[config], config)
    run_statistical_tests(all_results[config], config)
    print_sweep_summary(all_sweep_results[config], config)
    print_fold_ranking_details(all_rankings[config], config, N_TOP_FEATURES, N_BOTTOM_FEATURES)
    analyze_ranking_stability(all_rankings[config], config)
    generate_conclusion(all_results[config], config)

compare_channel_configs(all_results)

sys.stdout  = old_stdout
report_text = report.getvalue()

report_file = OUTPUT_DIR / 'analysis_report_pearson.txt'
with open(report_file, 'w') as f:
    f.write('HIGH vs LOW — PEARSON CORRELATION FEATURE SELECTION\n')
    f.write('Feature types ranked by avg |Pearson r| across all channels\n')
    f.write('Classifier input: top/bottom-N feat types × ALL channels\n')
    f.write('='*80 + '\n\n')
    f.write(f'Configs: {list(all_results.keys())}\n')
    f.write(f'N_TOP_FEATURES={N_TOP_FEATURES}, N_BOTTOM_FEATURES={N_BOTTOM_FEATURES}\n')
    f.write(f'N_FEATURE_SWEEP={N_FEATURE_SWEEP}\n')
    f.write('='*80 + '\n\n')
    f.write(report_text)

print(f'Report : {report_file}')
print(f'Outputs: {OUTPUT_DIR}')
print('\nFiles:')
for config in all_results.keys():
    print(f'  pearson_results_{config}_detailed.csv')
    print(f'  pearson_results_{config}_summary.csv')
    print(f'  pearson_confusion_{config}.png')
    print(f'  pearson_n_sweep_{config}.csv / .png')
    print(f'  pearson_stat_tests_{config}.csv')
    print(f'  pearson_global_vs_training_{config}.png')
print('  pearson_channel_config_comparison.png')
print('  analysis_report_pearson.txt')
print('\nDone.')